project_id = "rjhhrcoorayrqwotfqbc"

[auth]
enabled = true
site_url = "berabersatalim://"
additional_redirect_urls = ["berabersatalim://verify-email", "berabersatalim://reset-password", "berabersatalim://**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "60s"
otp_length = 6
otp_expiry = 3600

[auth.email.template.confirmation]
subject = "E-posta Adresinizi Doğrulayın - Beraber Satalım"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Şifre Sıfırlama - Beraber Satalım"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.invite]
subject = "Beraber Satalım'a Davet Edildiniz"
content_path = "./supabase/templates/invite.html"

[auth.email.template.magic_link]
subject = "Giriş Bağlantınız - Beraber Satalım"
content_path = "./supabase/templates/magic_link.html"

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.sessions]
timebox = 0
inactivity_timeout = 0

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.mfa.web_authn]
enroll_enabled = false
verify_enabled = false
