import type { TransactionType, PropertyType } from '@/types';

// ─── Şehirler ─────────────────────────────────────────

export const CITIES = ['İstanbul', 'Ankara', 'İzmir', 'Bursa', 'Antalya', 'Kocaeli', 'Muğla'] as const;
export type City = (typeof CITIES)[number];

// ─── İstanbul İlçeleri (39 ilçe) ──────────────────────

export const ISTANBUL_DISTRICTS = [
  'Adalar', 'Arnavutköy', 'Ataşehir', 'Avcılar', 'Bağcılar',
  'Bahçelievler', 'Bakırköy', 'Başakşehir', 'Bayrampaşa', 'Beşiktaş',
  'Beykoz', 'Beylikdüzü', 'Beyoğlu', 'Büyükçekmece', 'Çatalca',
  'Çekmeköy', 'Esenler', 'Esenyurt', 'Eyüpsultan', 'Fatih',
  'Gaziosmanpaşa', 'Güngören', 'Kadıköy', 'Kağıthane', 'Kartal',
  'Küçükçekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sarıyer',
  'Silivri', 'Sultanbeyli', 'Sultangazi', 'Şile', 'Şişli',
  'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu',
];

// ─── Çoklu Şehir İlçeleri ────────────────────────────

export const CITY_DISTRICTS: Record<string, string[]> = {
  'İstanbul': ISTANBUL_DISTRICTS,
  'Ankara': [
    'Altındağ', 'Çankaya', 'Çubuk', 'Etimesgut', 'Gölbaşı',
    'Keçiören', 'Mamak', 'Pursaklar', 'Sincan', 'Yenimahalle',
  ],
  'İzmir': [
    'Balçova', 'Bayraklı', 'Bornova', 'Buca', 'Çiğli',
    'Gaziemir', 'Karabağlar', 'Karşıyaka', 'Konak', 'Narlıdere',
  ],
  'Bursa': [
    'Büyükorhan', 'Gemlik', 'Gürsu', 'Harmancık', 'İnegöl',
    'İznik', 'Karacabey', 'Keles', 'Kestel', 'Mudanya',
    'Mustafakemalpaşa', 'Nilüfer', 'Orhaneli', 'Orhangazi',
    'Osmangazi', 'Yenişehir', 'Yıldırım',
  ],
  'Antalya': [
    'Akseki', 'Aksu', 'Alanya', 'Demre', 'Döşemealtı', 'Elmalı',
    'Finike', 'Gazipaşa', 'Gündoğmuş', 'İbradı', 'Kaş', 'Kemer',
    'Kepez', 'Konyaaltı', 'Korkuteli', 'Kumluca', 'Manavgat',
    'Muratpaşa', 'Serik',
  ],
  'Kocaeli': [
    'Başiskele', 'Çayırova', 'Darıca', 'Derince', 'Dilovası',
    'Gebze', 'Gölcük', 'İzmit', 'Kandıra', 'Karamürsel',
    'Kartepe', 'Körfez',
  ],
  'Muğla': [
    'Bodrum', 'Dalaman', 'Datça', 'Fethiye', 'Kavaklıdere',
    'Köyceğiz', 'Marmaris', 'Menteşe', 'Milas', 'Ortaca',
    'Seydikemer', 'Ula', 'Yatağan',
  ],
};

// ─── Backward compat ──────────────────────────────────

export const DISTRICTS = ['Hepsi', ...ISTANBUL_DISTRICTS] as string[];

// ─── İstanbul Mahalleler ──────────────────────────────

export const DISTRICT_NEIGHBORHOODS: Record<string, string[]> = {
  'Adalar': ['Burgazada', 'Büyükada', 'Heybeliada', 'Kınalıada'],
  'Arnavutköy': ['Bolluca', 'Dursunköy', 'Hadımköy', 'İmrahor', 'Karlıbayır', 'Taşoluk', 'Yassıören', 'Yeşilbayır'],
  'Ataşehir': ['Aşık Veysel', 'Atatürk', 'Barbaros', 'Batı Ataşehir', 'Esatpaşa', 'Fetih', 'İçerenköy', 'İnönü', 'Kayışdağı', 'Küçükbakkalköy', 'Mevlana', 'Mimar Sinan', 'Mustafa Kemal', 'Yenişehir', 'Yeni Çamlıca'],
  'Avcılar': ['Ambarlı', 'Cihangir', 'Denizköşkler', 'Firuzköy', 'Gümüşpala', 'Merkez', 'Mustafa Kemal Paşa', 'Tahtakale', 'Üniversite', 'Yeşilkent'],
  'Bağcılar': ['Barbaros', 'Bağlar', 'Çınar', 'Demirkapı', 'Evren', 'Fatih', 'Fevzi Çakmak', 'Güneşli', 'Hürriyet', 'İnönü', 'Kazım Karabekir', 'Kemalpaşa', 'Kirazlı', 'Mahmutbey', 'Merkez', 'Sancaktepe', 'Yavuz Selim', 'Yenigün', 'Yenimahalle', 'Yıldıztepe'],
  'Bahçelievler': ['Bahçelievler', 'Çobançeşme', 'Fevzi Çakmak', 'Hürriyet', 'Kocasinan', 'Siyavuşpaşa', 'Soganli', 'Şirinevler', 'Yenibosna', 'Zafer'],
  'Bakırköy': ['Ataköy 1. Kısım', 'Ataköy 2-5-6. Kısım', 'Ataköy 3-4-11. Kısım', 'Ataköy 7-8-9-10. Kısım', 'Basınköy', 'Cevizlik', 'Florya', 'Kartaltepe', 'Mahmutbey', 'Osmaniye', 'Sakızağacı', 'Şenlikköy', 'Yeşilköy', 'Yeşilyurt', 'Zuhuratbaba'],
  'Başakşehir': ['Altınşehir', 'Başak', 'Başakşehir', 'Güvercintepe', 'Kayabaşı', 'Kayaşehir', 'Şahintepe', 'Ziya Gökalp'],
  'Bayrampaşa': ['Altıntepsi', 'Cevatpaşa', 'İsmetpaşa', 'Kocatepe', 'Muratpaşa', 'Orta', 'Terazidere', 'Vatan', 'Yenidoğan', 'Yıldırım'],
  'Beşiktaş': ['Abbasağa', 'Akatlar', 'Arnavutköy', 'Bebek', 'Cihannüma', 'Dikilitaş', 'Etiler', 'Gayrettepe', 'Konaklar', 'Kuruçeşme', 'Levent', 'Levazım', 'Muradiye', 'Nisbetiye', 'Ortaköy', 'Sinanpaşa', 'Türkali', 'Ulus', 'Vişnezade', 'Yıldız'],
  'Beykoz': ['Acarlar', 'Anadoluhisarı', 'Çavuşbaşı', 'Çubuklu', 'Gümüşsuyu', 'İncirköy', 'Kanlıca', 'Kavacık', 'Paşabahçe', 'Polonezköy', 'Riva', 'Rüzgarlıbahçe'],
  'Beylikdüzü': ['Adnan Kahveci', 'Barış', 'Büyükşehir', 'Cumhuriyet', 'Dereağzı', 'Gürpınar', 'İnönü', 'Kavakpınar', 'Kavaklı', 'Marmara', 'Sahil', 'Yakuplu'],
  'Beyoğlu': ['Asmalımescit', 'Cihangir', 'Çukurcuma', 'Firuzağa', 'Galata', 'Gümüşsuyu', 'Kasımpaşa', 'Kulaksız', 'Ömeravni', 'Pürtelaş', 'Tarlabaşı', 'Tomtom'],
  'Büyükçekmece': ['Atatürk', 'Bahçelievler', 'Batıköy', 'Cumhuriyet', 'Fatih', 'Kamiloba', 'Mimarsinan', 'Muratbey', 'Pınartepe', 'Türkoba'],
  'Çatalca': ['Çatalca Merkez', 'Ferhatpaşa', 'Kaleiçi', 'Muratbey', 'Ovayenice', 'Subaşı'],
  'Çekmeköy': ['Alemdağ', 'Çamlık', 'Hamidiye', 'Mehmet Akif', 'Merkez', 'Mimar Sinan', 'Ömerli', 'Sultançiftliği', 'Taşdelen'],
  'Esenler': ['Atışalanı', 'Birlik', 'Davutpaşa', 'Fatih', 'Fevzi Çakmak', 'Havaalanı', 'Kâzım Karabekir', 'Menderes', 'Namık Kemal', 'Oruç Reis', 'Tuna', 'Yavuz Selim'],
  'Esenyurt': ['Ardıçlı', 'Bahçeşehir 1. Kısım', 'Bahçeşehir 2. Kısım', 'Fatih', 'İnönü', 'İstiklal', 'Kıraç', 'Mehterçeşme', 'Namık Kemal', 'Pınar', 'Saadetdere', 'Talatpaşa', 'Üçevler', 'Yenikent', 'Yeşilkent'],
  'Eyüpsultan': ['Akşemsettin', 'Alibeyköy', 'Çırçır', 'Defterdar', 'Emniyettepe', 'Göktürk', 'İslambey', 'Kemerburgaz', 'Nişancı', 'Pirinççi', 'Rami', 'Silahtarağa', 'Topçular', 'Yeşilpınar'],
  'Fatih': ['Aksaray', 'Balat', 'Beyazıt', 'Cankurtaran', 'Cerrahpaşa', 'Çarşamba', 'Edirnekapı', 'Fener', 'Haseki', 'Karagümrük', 'Kumkapı', 'Laleli', 'Saraçhane', 'Sultanahmet', 'Süleymaniye', 'Vefa', 'Yedikule', 'Zeyrek'],
  'Gaziosmanpaşa': ['Bağlarbaşı', 'Barbaros', 'Hürriyet', 'Karlıtepe', 'Karadeniz', 'Kazım Karabekir', 'Merkez', 'Mevlana', 'Sarıgöl', 'Yenimahalle', 'Yıldıztabya'],
  'Güngören': ['Akıncılar', 'Güneştepe', 'Gençosman', 'Güven', 'Haznedar', 'Mareşal Çakmak', 'Mehmet Nesih Özmen', 'Merkez', 'Sanayi', 'Tozkoparan'],
  'Kadıköy': ['Acıbadem', 'Bostancı', 'Caferağa', 'Caddebostan', 'Dumlupınar', 'Erenköy', 'Fenerbahçe', 'Feneryolu', 'Fikirtepe', 'Göztepe', 'Hasanpaşa', 'İçerenköy', 'Koşuyolu', 'Kozyatağı', 'Merdivenköy', 'Moda', 'Osmanağa', 'Rasimpaşa', 'Sahrayıcedit', 'Suadiye', 'Yeldeğirmeni', 'Zühtüpaşa'],
  'Kağıthane': ['Çağlayan', 'Çeliktepe', 'Emniyet', 'Gültepe', 'Hamidiye', 'Harmantepe', 'Hürriyet', 'Mehmet Akif Ersoy', 'Merkez', 'Nurtepe', 'Ortabayır', 'Sanayi', 'Seyrantepe', 'Şirintepe', 'Talatpaşa', 'Yahya Kemal'],
  'Kartal': ['Atalar', 'Cevizli', 'Çavuşoğlu', 'Esentepe', 'Hürriyet', 'Karlıktepe', 'Kordonboyu', 'Orhantepe', 'Soğanlık', 'Topselvi', 'Uğur Mumcu', 'Yakacık', 'Yukarı'],
  'Küçükçekmece': ['Atatürk', 'Beşyol', 'Cennet', 'Cumhuriyet', 'Fatih', 'Fevzi Çakmak', 'Gültepe', 'Halkalı', 'İnönü', 'Kanarya', 'Kemalpaşa', 'Mehmet Akif', 'Söğütlüçeşme', 'Yarımburgaz', 'Yeşilova'],
  'Maltepe': ['Altayçeşme', 'Altıntepe', 'Aydınevler', 'Bağlarbaşı', 'Başıbüyük', 'Cevizli', 'Çınar', 'Dragos', 'Esenkent', 'Feyzullah', 'Fındıklı', 'Girne', 'Gülsuyu', 'Gülensu', 'İdealtepe', 'Küçükyalı', 'Yalı', 'Zümrütevler'],
  'Pendik': ['Ahmet Yesevi', 'Bahçelievler', 'Batı', 'Çamçeşme', 'Çınardere', 'Doğu', 'Dumlupınar', 'Esenler', 'Esenyalı', 'Güllü Bağlar', 'Güzelyalı', 'Kaynarca', 'Kurtköy', 'Ramazanoğlu', 'Sapanbağları', 'Velibaba', 'Yenişehir'],
  'Sancaktepe': ['Abdurrahman Gazi', 'Akpınar', 'Atatürk', 'Emek', 'Eyüp Sultan', 'Fatih', 'İnönü', 'Meclis', 'Merve', 'Osmangazi', 'Sarıgazi', 'Veysel Karani', 'Yenidoğan'],
  'Sarıyer': ['Ayazağa', 'Bahçeköy', 'Baltalimanı', 'Büyükdere', 'Çamlıtepe', 'Darüşşafaka', 'Emirgan', 'Fatih Sultan Mehmet', 'İstinye', 'Kireçburnu', 'Maslak', 'Pınar', 'PTT Evleri', 'Reşitpaşa', 'Rumelihisarı', 'Rumeli Kavağı', 'Tarabya', 'Yeniköy', 'Zekeriyaköy'],
  'Silivri': ['Alibey', 'Cumhuriyet', 'Fatih', 'Merkez', 'Mimarsinan', 'Piri Mehmet Paşa', 'Selimpaşa', 'Yolçatı'],
  'Sultanbeyli': ['Abdurrahman Gazi', 'Battalgazi', 'Fatih', 'Hamidiye', 'Hasanpaşa', 'Mecidiye', 'Mehmet Akif', 'Mimar Sinan', 'Necip Fazıl', 'Orhangazi', 'Turgut Reis', 'Yavuz Selim'],
  'Sultangazi': ['50. Yıl', 'Cebeci', 'Cumhuriyet', 'Esentepe', 'Gazi', 'Habibler', 'İsmetpaşa', 'Malkoçoğlu', 'Sultançiftliği', 'Uğur Mumcu', 'Yayla', 'Yunus Emre', 'Zübeyde Hanım'],
  'Şile': ['Ağva', 'Balibey', 'Hacıkasım', 'Kumbaba', 'Merkez', 'Sahilköy', 'Üvezli'],
  'Şişli': ['Bomonti', 'Cumhuriyet', 'Dikilitaş', 'Duatepe', 'Esentepe', 'Feriköy', 'Fulya', 'Gülbahar', 'Halaskargazi', 'Harbiye', 'İnönü', 'İstiklal', 'Kuştepe', 'Mecidiyeköy', 'Meşrutiyet', 'Nişantaşı', 'Osmanbey', 'Paşa', 'Teşvikiye', 'Yayla'],
  'Tuzla': ['Aydınlı', 'Aydıntepe', 'Cami', 'Evliya Çelebi', 'Fatih', 'İçmeler', 'İstasyon', 'Mescit', 'Mimar Sinan', 'Orhanlı', 'Postane', 'Şifa', 'Yayla'],
  'Ümraniye': ['Armağanevler', 'Aşağı Dudullu', 'Atatürk', 'Çakmak', 'Çamlık', 'Esenevler', 'Esenşehir', 'Hekimbaşı', 'İnkılap', 'İstiklal', 'Kazım Karabekir', 'Madenler', 'Namık Kemal', 'Parseller', 'Saray', 'Site', 'Tantavi', 'Tatlısu', 'Tepetarla', 'Yukarı Dudullu'],
  'Üsküdar': ['Acıbadem', 'Altunizade', 'Aziz Mahmut Hüdayi', 'Bahçelievler', 'Beylerbeyi', 'Burhaniye', 'Çengelköy', 'Ferah', 'İcadiye', 'Kandilli', 'Kısıklı', 'Kuzguncuk', 'Mimar Sinan', 'Salacak', 'Selimiye', 'Ünalan', 'Validei Atik', 'Vaniköy', 'Yavuztürk'],
  'Zeytinburnu': ['Beştelsiz', 'Çırpıcı', 'Gökalp', 'Kazlıçeşme', 'Maltepe', 'Merkezefendi', 'Nuripaşa', 'Seyitnizam', 'Sümer', 'Telsiz', 'Veliefendi', 'Yeşiltepe'],
};

// ─── Kadıköy backward compat ──────────────────────────
export const KADIKOY_NEIGHBORHOODS = DISTRICT_NEIGHBORHOODS['Kadıköy'];

// ─── Ankara Mahalleler ────────────────────────────────

export const ANKARA_NEIGHBORHOODS: Record<string, string[]> = {
  'Altındağ': ['Aktaş', 'Aydınlıkevler', 'Başpınar', 'Battalgazi', 'Doğantepe', 'Gülpınar', 'Hacettepe', 'Karapürçek', 'Siteler', 'Ulubey'],
  'Çankaya': ['Bahçelievler', 'Balgat', 'Çayyolu', 'Dikmen', 'Emek', 'Gaziosmanpaşa', 'Kavaklıdere', 'Kızılay', 'Oran', 'Çukurambar', 'Yaşamkent'],
  'Çubuk': ['Aşağıçavundur', 'Cumhuriyet', 'Dumlupınar', 'Mehmet Akif Ersoy', 'Merkez'],
  'Etimesgut': ['30 Ağustos', 'Ahi Mesut', 'Alsancak', 'Bağlıca', 'Elvankent', 'Eryaman', 'Topçu', 'Yapracık'],
  'Gölbaşı': ['Bahçelievler', 'Eymir', 'Gaziosmanpaşa', 'İncek', 'Karşıyaka', 'Kızılcaşar', 'Tuluntaş'],
  'Keçiören': ['Aktepe', 'Bağlum', 'Etlik', 'İncirli', 'Kalaba', 'Kanuni', 'Kuşcağız', 'Ovacık', 'Subayevleri', 'Ufuktepe'],
  'Mamak': ['Abidinpaşa', 'Akdere', 'Boğaziçi', 'Cengizhan', 'Durali Alıç', 'Eğitim', 'Fahri Korutürk', 'Kutlu', 'Tuzluçayır'],
  'Pursaklar': ['Altınova', 'Fatih', 'Merkez', 'Saray', 'Yukarı Murtaza'],
  'Sincan': ['Atatürk', 'Fatih', 'Lale', 'Mareşal Çakmak', 'Pınarbaşı', 'Tandoğan', 'Törekent', 'Yenikent'],
  'Yenimahalle': ['Batıkent', 'Çamlıca', 'Demetevler', 'Gayret', 'Karşıyaka', 'Macunköy', 'Mehmet Akif Ersoy', 'Ostim', 'Şentepe'],
};

export const IZMIR_NEIGHBORHOODS: Record<string, string[]> = {
  'Balçova': ['Bahçelerarası', 'Çetin Emeç', 'Ege', 'Fevzi Çakmak', 'İnciraltı', 'Korutürk', 'Onur', 'Teleferik'],
  'Bayraklı': ['Adalet', 'Bayraklı', 'Çiçek', 'Manavkuyu', 'Mansuroğlu', 'Onur', 'Osmangazi', 'Salhane', 'Turan'],
  'Bornova': ['Altındağ', 'Çamdibi', 'Doğanlar', 'Ergene', 'Evka-3', 'Kazımdirik', 'Kemalpaşa', 'Laka', 'Mevlana', 'Yeşilova'],
  'Buca': ['Adatepe', 'Çamlıkule', 'Efes', 'Gaziler', 'İnkılap', 'Kozağaç', 'Şirinyer', 'Tınaztepe', 'Yasin'],
  'Çiğli': ['Atatürk', 'Balatçık', 'Egekent', 'Evka-5', 'Harmandere', 'Küçükçiğli', 'Ova'],
  'Gaziemir': ['Aktepe', 'Atıfbey', 'Binbaşı Reşatbey', 'Gazi', 'Sakarya', 'Sevgi', 'Yeşil'],
  'Karabağlar': ['Bozyaka', 'Cennetçeşme', 'Günaltay', 'Limontepe', 'Peker', 'Salih Omurtak', 'Üçkuyular', 'Uzundere'],
  'Karşıyaka': ['Aksoy', 'Alaybey', 'Bostanlı', 'Çarşı', 'Dedebaşı', 'Donanmacı', 'Mavişehir', 'Nergiz', 'Tersane', 'Yalı'],
  'Konak': ['Alsancak', 'Basmane', 'Çankaya', 'Güzelyalı', 'Hatay', 'Kahramanlar', 'Kemeraltı', 'Konak', 'Pasaport', 'Üçkuyular'],
  'Narlıdere': ['Atatürk', 'Çatalkaya', 'Huzur', 'Limanreis', 'Narlı', 'Sahilevleri'],
};

// ─── Bursa Mahalleler (17 ilçe) ─────────────────────

export const BURSA_NEIGHBORHOODS: Record<string, string[]> = {
  'Osmangazi': [
    'Adalet', 'Ahmetbey', 'Ahmetpaşa', 'Akpınar', 'Aksungur', 'Aktarhüssam',
    'Alaaddin', 'Alacahırka', 'Alacamescit', 'Alaşarköy', 'Alemdar', 'Alipaşa',
    'Altınova', 'Altıparmak', 'Armutköy', 'Atıcılar', 'Avdancık',
    'Bağlarbaşı', 'Bağlı', 'Bahar', 'Başaran', 'Büyükdeliller',
    'Çağlayan', 'Çaybaşı', 'Çekirge', 'Çeltikköy', 'Çırpan', 'Çiftehavuzlar', 'Çirişhane', 'Çukurcaköy',
    'Dağakça', 'Demirkapı', 'Demirtaş Barbaros', 'Demirtaş Cumhuriyet', 'Demirtaş Dumlupınar', 'Demirtaş Sakarya', 'Demirtaşpaşa',
    'Dereçavuşköy', 'Dikkaldırım', 'Doburca', 'Doğanbey', 'Doğancı', 'Doğanevler', 'Dürdane',
    'Ebu İshak', 'Elmaçukur', 'Elmasbahçeler', 'Emek Adnan Menderes', 'Emek Fatih Sultan Mehmet', 'Emek Zekai Gümüşdiş',
    'Fatih', 'Gaziakdemir', 'Geçit', 'Gökçeören', 'Gülbahçe', 'Gündoğdu', 'Güneştepe', 'Güneybayır', 'Güneybudaklar',
    'Hacı İlyas', 'Hamitler', 'Hamzabey', 'Hocaalizade', 'Hocahasan', 'Hüdavendigar', 'Hürriyet', 'Hüseyinalan',
    'İbrahimpaşa', 'İnkaya', 'İntizam', 'İsmetiye', 'İstiklal', 'İvazpaşa',
    'Karabalçık', 'Karaıslah', 'Kavaklı', 'Kayıhan', 'Kemerçeşme', 'Kırcaali', 'Kirazlı', 'Kiremitçi',
    'Kocanaip', 'Koğukçınar', 'Kuruçeşme', 'Küçükbalıklı', 'Küçükdeliller', 'Kükürtlü', 'Küplüpınar',
    'Maksem', 'Mehmet Akif', 'Mollafenari', 'Mollagürani', 'Muradiye', 'Mürseller',
    'Nalbantoğlu', 'Namık Kemal', 'Nilüferköy',
    'Orhanbey', 'Osmangazi', 'Ovaakça Çeşmebaşı', 'Ovaakça Eğitim', 'Ovaakça Merkez', 'Ovaakça Santral',
    'Panayır', 'Pınarbaşı', 'Reyhan',
    'Sakarya', 'Santral Garaj', 'Seç', 'Seferişıklar', 'Selamet', 'Selçukgazi', 'Selimiye', 'Sırameşeler',
    'Soğanlı', 'Soğukkuyu', 'Soğukpınar',
    'Şehabettinpaşa', 'Şehreküstü',
    'Tahtakale', 'Tayakadın', 'Tuna', 'Tuzaklı', 'Tuzpazarı',
    'Ulu', 'Uluçam',
    'Veysel Karani',
    'Yahşibey', 'Yenibağlar', 'Yeniceabat', 'Yenikaraman', 'Yenikent', 'Yeşilova', 'Yiğitali', 'Yunuseli', 'Zafer',
  ],
  'Nilüfer': [
    '19 Mayıs', '23 Nisan', '29 Ekim', '30 Ağustos Zafer',
    'Ahmet Yesevi', 'Akçalar', 'Alaaddınbey', 'Altınşehir', 'Ataevler', 'Atlas', 'Ayvaköy',
    'Badırga', 'Balat', 'Balkan', 'Barış', 'Başköy', 'Beşevler', 'Büyükbalıklı',
    'Cumhuriyet', 'Çalı', 'Çamlıca', 'Çatalağıl', 'Çaylı',
    'Dağyenice', 'Demirci', 'Doğanköy', 'Dumlupınar',
    'Ertuğrul', 'Esentepe',
    'Fadıllı', 'Fethiye',
    'Gökçe', 'Gölyazı', 'Görükle', 'Gümüştepe', 'Güngören',
    'Hasanağa',
    'Işıktepe', 'İhsaniye', 'İnegazi', 'İrfaniye',
    'Kadriye', 'Karacaoba', 'Karaman', 'Kayapa', 'Kızılcıklı', 'Konak', 'Konaklı', 'Korubaşı', 'Kurtuluş', 'Kuruçeşme', 'Kültür',
    'Makşempınarı', 'Minareliçavuş',
    'Odunluk', 'Özlüce',
    'Tahtalı',
    'Unçukuru', 'Üçevler', 'Üçpınar', 'Ürünlü',
    'Yaylacık', 'Yolçatı', 'Yüzüncüyıl',
  ],
  'Yıldırım': [
    '152 Evler', '75. Yıl',
    'Akçağlayan', 'Anadolu', 'Arabayatağı',
    'Bağlaraltı', 'Balaban', 'Baruthane', 'Beyazıt',
    'Cumalıkızık', 'Çelebi Mehmet', 'Çınarönü',
    'Davutdede', 'Davutkadı', 'Değirmenlikızık', 'Değirmenönü', 'Demetevler', 'Duaçınarı',
    'Eğitim', 'Emirsultan', 'Erikli', 'Ertuğrulgazi', 'Esenevler',
    'Fidyekızık',
    'Güllük',
    'Hacıseyfettin', 'Hacivat', 'Hamamlıkızık', 'Hocataşkın',
    'İsabey',
    'Kaplıkaya', 'Karaağaç', 'Karamazak', 'Karapınar', 'Kazım Karabekir', 'Kurtoğlu',
    'Maltepe', 'Mehmet Akif Ersoy', 'Mevlana', 'Meydancık', 'Millet', 'Mimar Sinan', 'Mollaarap', 'Musababa',
    'Namazgah',
    'Ortabağlar',
    'Piremir',
    'Sakarya', 'Samanlı', 'Selçukbey', 'Selimzade', 'Sıracevizler', 'Sinandede', 'Siteler', 'Şirinevler', 'Şükraniye',
    'Teferrüç',
    'Ulus', 'Umurbey',
    'Vakıf', 'Vatan',
    'Yavuz Selim', 'Yediselvilier', 'Yenimahalle', 'Yeşil', 'Yeşilyayla', 'Yıldırım', 'Yiğitler', 'Yunusemre',
    'Zeyniler', 'Zümrütevler',
  ],
  'İnegöl': [
    'Akbaşlar', 'Akhisar', 'Akıncılar', 'Alibey', 'Aşağıballık',
    'Babaoğlu', 'Bahariye', 'Bahçekaya', 'Baykoca', 'Bayramşah', 'Bilalköy', 'Boğazköy', 'Burhaniye',
    'Cemiyet', 'Cerrah', 'Cuma', 'Cumhuriyet', 'Çavuşköy', 'Çaylıca', 'Çayyaka', 'Çeltikçi', 'Çiftlikköy', 'Çitli',
    'Deydınler', 'Dipsizgöl', 'Doğanyurdu', 'Dömez',
    'Edebey', 'Elmaçayır', 'Ertuğrulgazi', 'Esenköy', 'Esentepe', 'Eski Bahçekaya', 'Eskikaracakaya', 'Eskiköy', 'Eymir',
    'Fatih', 'Fevziye', 'Fındıklı',
    'Gazelli', 'Gedikpınar', 'Gülbahçe', 'Gündüzlü', 'Güneykestane', 'Güzelyurt',
    'Hacıkara', 'Halhalca', 'Hamamlı', 'Hamidiye', 'Hamitabat', 'Hamzabey', 'Hasanpaşa', 'Hayriye', 'Hilmiye', 'Hocaköy', 'Huzur',
    'İclaliye', 'İhsaniye', 'İsaören',
    'Karagölet', 'Karahasanlar', 'Karakadı', 'Karalar', 'Kayapınar', 'Kemalpaşa', 'Kestanealanı', 'Kınık', 'Kıran', 'Kocakonak', 'Konurlar', 'Kozluca', 'Kulaca', 'Kurşunlu', 'Küçükyenice',
    'Lütfiye',
    'Madenköy', 'Mahmudiye', 'Mesudiye', 'Mezit', 'Muratbey',
    'Olukman', 'Orhaniye', 'Ortaköy', 'Osmaniye', 'Osmaniyeköy', 'Özlüce',
    'Paşaören',
    'Rüştiye',
    'Saadet', 'Sarıpınar', 'Sinanbey', 'Soğukdere', 'Sulhiye', 'Sultaniye', 'Sungurpaşa', 'Süle', 'Süleymaniye', 'Sülüklügöl', 'Süpürtü',
    'Şehitler', 'Şipali',
    'Tahtaköprü', 'Tekkeköy', 'Tokuş', 'Turgutalp', 'Turgutalpköy', 'Tuzla', 'Tüfekçikonak',
    'Yeni', 'Yenice', 'Yeniceköy', 'Yeniköy', 'Yeniyörük', 'Yiğit', 'Yukarıballık', 'Yunusemre',
  ],
  'Gemlik': [
    'Adliye', 'Ata', 'Balıkpazarı', 'Büyükkumla',
    'Cihatlı', 'Cumhuriyet',
    'Demirsubaşı', 'Dr. Ziya Kaya',
    'Engürücük', 'Eşref Dinçer',
    'Feyziye', 'Fındıcak',
    'Gençali', 'Güvenli',
    'Halitpaşa', 'Hamidiye', 'Hamidiyeköy', 'Haydariye', 'Hisar',
    'Karacaali', 'Katırlı', 'Kayhan', 'Kumla', 'Kurşunlu', 'Kurtul', 'Küçükkumla',
    'Muratoba',
    'Narlı',
    'Orhaniye', 'Osmaniye',
    'Şahinyurdu', 'Şükriye',
    'Umurbey',
    'Yeni', 'Yeniköy',
  ],
  'Mudanya': [
    'Akköy', 'Altıntaş', 'Aydınpınar',
    'Bademli', 'Balabancık',
    'Çağrışan', 'Çamlık', 'Çayönü', 'Çekirice', 'Çepni', 'Çınarlı',
    'Dedeköy', 'Dereköy',
    'Eğerce', 'Emirleryenicesi', 'Esence', 'Evciler',
    'Göynüklü', 'Güzelyalı Burgaz', 'Güzelyalı Eğitim', 'Güzelyalı Siteler', 'Güzelyalı Yalı',
    'Halitpaşa', 'Hançerli', 'Hasanbey', 'Hasköy',
    'Işıklı', 'İpekyayla',
    'Kaymakoba', 'Kumyaka', 'Küçükyenice',
    'Mesudiye', 'Mirzaoba', 'Mürsel', 'Mütareke',
    'Orhaniye', 'Ömerbey',
    'Söğütpınar', 'Şükrüçavuş',
    'Tirilye',
    'Ülkü',
    'Yalıçiftlik', 'Yaman', 'Yaylacık', 'Yeni', 'Yörükali', 'Yörükyenicesi',
  ],
  'Gürsu': [
    'Adaköy', 'Ağaköy',
    'Canbazlarköyü',
    'Dışkayaköyü',
    'Ericekköyü',
    'Hasanköy',
    'İğdirköyü', 'İpekyolu', 'İstiklal',
    'Karahıdırköyü', 'Kazıklıköyü', 'Kumlukalan', 'Kurtuluş',
    'Yenidoğan',
    'Zafer',
  ],
  'Kestel': [
    'Ağlaşan', 'Ahmetvefikpaşa', 'Aksu', 'Alaçam',
    'Babasultan', 'Barakfakih', 'Burhaniye',
    'Çataltepe',
    'Derekızık', 'Dudaklı',
    'Erdoğan', 'Esentepe',
    'Gölbaşı', 'Gölcük', 'Gözede',
    'Kale', 'Kayacık', 'Kazancı', 'Kozluören',
    'Lütfiye',
    'Narlıdere', 'Nüzhetiye',
    'Orhaniye', 'Osmaniye',
    'Saitabat', 'Sayfiye', 'Serme', 'Seymen', 'Soğuksu', 'Şevketiye',
    'Turanköy',
    'Ümitalan',
    'Vanımehmet',
    'Yağmurlu', 'Yeni',
  ],
  'Karacabey': [
    'Abdullahpaşa', 'Akçakoyun', 'Akçasusurluk', 'Akhisar', 'Arız',
    'Bakırköy', 'Ballıkaya', 'Bayramdere', 'Beylik', 'Boğazköy',
    'Canbalı', 'Canbaz', 'Çamlıca', 'Çarıkköy', 'Çavuş', 'Çeşnigir',
    'Dağesemen', 'Dağkadı', 'Danişment', 'Doğla', 'Drama',
    'Ekinli', 'Ekmekçi', 'Emirsultan', 'Esentepe', 'Eskikaraağaç', 'Eskisarıbey',
    'Fevzipaşa',
    'Garipçe', 'Gazi', 'Gölecik', 'Gölkıyı', 'Gönü', 'Güngörmez',
    'Hamidiye', 'Harmanlı', 'Hayırlar', 'Hotanlı', 'Hüdavendigar', 'Hürriyet',
    'İkizce', 'İnkaya', 'İsmetpaşa',
    'Karacaahmet', 'Karakoca', 'Karasu', 'Kedikaya', 'Keşlik', 'Kıranlar', 'Kulakpınar', 'Kurşunlu', 'Küçükkaraağaç',
    'Mamuriye', 'Mecidiye', 'Muratlı',
    'Nasrettin',
    'Okçular', 'Orhaniye', 'Ortasarıbey', 'Ova Hamidiye', 'Ovaesemen', 'Örencik',
    'Runguşpaşa',
    'Saadet', 'Sazlıca', 'Selimiye', 'Seyran', 'Sırabademler', 'Subaşı', 'Sultaniye',
    'Şahinköy', 'Şahmelek',
    'Tabaklar', 'Taşlık', 'Taşpınar', 'Tavşanlı', 'Tophisar',
    'Uluabat',
    'Yarış', 'Yeni', 'Yenice', 'Yenikaraağaç', 'Yenisarıbey', 'Yeşildere', 'Yolağzı',
  ],
  'Orhangazi': [
    'Akharem', 'Arapzade',
    'Bayırköy',
    'Camii Kebir', 'Cihanköy', 'Çakırlı', 'Çeltikçi',
    'Dutluca',
    'Fatih', 'Fındıklı',
    'Gedelek', 'Gemiç', 'Gölyaka', 'Gürle',
    'Hamzalı', 'Heceler', 'Hürriyet',
    'Karsak', 'Keramet',
    'Mahmudiye', 'Muradiye',
    'Narlıca',
    'Ortaköy', 'Örnekköy',
    'Paşapınar',
    'Sölöz',
    'Tekke',
    'Üreğil',
    'Yenigürle', 'Yeniköy', 'Yenisölöz',
  ],
  'İznik': [
    'Aydınlar', 'Bayındır', 'Beyler', 'Boyalıca',
    'Candarlı', 'Çakırca', 'Çamdibi', 'Çamoluk', 'Çampınar', 'Çiçekli',
    'Derbent', 'Dereköy', 'Dırazali',
    'Elbeyli', 'Elmalı', 'Eşrefzade',
    'Göllüce', 'Gürmüzlü',
    'Hacıosman', 'Hisardere', 'Hocaköy',
    'İhsaniye', 'İnikli',
    'Karatekin', 'Kaynarca', 'Kırıntı', 'Kutluca',
    'Mahmudiye', 'Mahmut Çelebi', 'Mecidiye', 'Mustafa Kemal Paşa', 'Mustafali', 'Müşküle',
    'Orhaniye', 'Osmaniye', 'Ömerli',
    'Sansarak', 'Sarıağıl', 'Selçuk', 'Süleymaniye',
    'Şerefiye',
    'Tacir',
    'Yeni', 'Yenişerefiye', 'Yeşil Camii', 'Yürükler',
  ],
  'Mustafakemalpaşa': [
    'Adaköy', 'Adalet', 'Ağaçlı', 'Akarca', 'Akçapınar', 'Alacaat', 'Aliseydi', 'Alpağut', 'Aralık', 'Aşağıbalı', 'Atariye', 'Atatürk', 'Ayaz',
    'Bahariye', 'Barış', 'Behram', 'Boğaz', 'Bostandere', 'Bük',
    'Camandar', 'Cumhuriyet', 'Çakallar', 'Çaltılıbük', 'Çamlıca', 'Çardakbelen', 'Çavuş', 'Çeltikçi', 'Çırpan', 'Çivilikçam', 'Çömlekçi', 'Çördük',
    'Dallıca', 'Demirdere', 'Demireli', 'Dere', 'Derecik', 'Derekadı', 'Deveckonağı', 'Doğanalan', 'Doğancı', 'Dorak', 'Döllük', 'Durumtay',
    'Eskibalçık', 'Eskikızılelma',
    'Fevzidede', 'Fındıcak',
    'Garipçetekke', 'Güller', 'Güllüce', 'Gündoğdu', 'Güveçdere', 'Güvem',
    'Hacıahmet', 'Hacıali', 'Hamidiye', 'Hamidiyeköyü', 'Hamzabey', 'Hisaraltı',
    'Işıklar', 'İlyasçılar', 'İncealipınar',
    'Kabulbaba', 'Kadirçeşme', 'Kapaklıoluk', 'Karacalar', 'Karaköy', 'Karaoğlan', 'Karaorman', 'Karapınar', 'Kayabaşı', 'Kazanpınar', 'Keltaş', 'Kestelek', 'Killik', 'Kocakoru', 'Kosova', 'Koşuboğazı', 'Kömürcükadı', 'Körekem', 'Kösehoroz', 'Kumkadı', 'Kurşunlu',
    'Lalaşahin', 'Lütfiye',
    'Melik', 'Muradiyesarnıç',
    'Ocaklı', 'Onaç', 'Orhaniye', 'Ormankadı', 'Orta', 'Osmaniye', 'Ovaazatlı', 'Ömeraltı',
    'Paşalar',
    'Sarımustafalar', 'Selimiye', 'Sincansarnıç', 'Soğucak', 'Soğukpınar', 'Söğütalan', 'Sünlük',
    'Şapçı', 'Şehriman', 'Şerefiye', 'Şevketiye', 'Şeyhmüftü',
    'Taşköprü', 'Taşpınar', 'Tatkavaklı', 'Tepecik', 'Tırnova',
    'Uğurlupınar', 'Üçbeyli',
    'Vıraca',
    'Yalıntaş', 'Yamanlı', 'Yavelli', 'Yaylacayır', 'Yenibalçık', 'Yenice', 'Yenidere', 'Yenikızılelma', 'Yeşilova', 'Yoncaağaç', 'Yukarıbalı', 'Yumurcaklı', 'Yunus Emre', 'Yüzbaşı Sabribey',
    'Züferbey',
  ],
  'Yenişehir': [
    'Afşar', 'Akbıyık', 'Akçapınar', 'Akdere', 'Alaylı', 'Ayaz', 'Aydoğdu',
    'Barcın', 'Beypınar', 'Burcun',
    'Cihadiye', 'Çamönü', 'Çardak', 'Çayır', 'Çayırlı', 'Çelebi', 'Çeltikçi', 'Çiçeközü',
    'Demirboga', 'Dereköy',
    'Ebeköy', 'Eğerce',
    'Fethiye',
    'Gökçesu', 'Gündoğan', 'Günece',
    'Hayriye', 'Hıdırbalı',
    'İncirli',
    'Karaamca', 'Karabahadır', 'Karacaahmet', 'Karacaali', 'Karaköy', 'Karasıl', 'Kavaklı', 'Kıblepınar', 'Kızılhisar', 'Kızılköy', 'Kirazlıyayla', 'Koyunhisar', 'Kozdere', 'Köprühisar', 'Kurtuluş',
    'Mahmudiye', 'Marmaracık', 'Mecidiye', 'Menteşe',
    'Orhaniye', 'Osmaniye',
    'Papatya', 'Paşayayla',
    'Reşadiye',
    'Selimiye', 'Söylemiş', 'Subaşı', 'Süleymaniye',
    'Tabakhane', 'Terziler', 'Toprakdere', 'Toprakocak',
    'Ulucami',
    'Yarhisar', 'Yazılı', 'Yeni', 'Yenigün', 'Yeniköy', 'Yıldırım', 'Yılmaz', 'Yolören', 'Yüzüncüyıl',
  ],
  'Büyükorhan': [
    'Akçasaz', 'Aktaş', 'Armutçuk',
    'Bademlik', 'Balaban', 'Bayındır', 'Burunca',
    'Cumhuriyet', 'Çakıryenice', 'Çeribaşı',
    'Danacılar', 'Danaçalı', 'Demirler', 'Derecik', 'Durhasan', 'Düğüncüler',
    'Elekçalı', 'Ericek',
    'Gedikler', 'Geynik',
    'Hacıahmetler', 'Hacılar', 'Hemşeriler', 'Hocahasan',
    'İsmetiye',
    'Karaağız', 'Karaçukur', 'Karalar', 'Kayapa', 'Kınık', 'Kuşlar',
    'Mazlumlar',
    'Orhan', 'Osmanlar', 'Örencik', 'Özlüce',
    'Perçin', 'Pınarköy', 'Pirebeyler',
    'Sarnıç',
    'Tekerler',
    'Yenice', 'Zaferiye',
  ],
  'Harmancık': [
    'Akpınar', 'Alutça',
    'Balatdanişment', 'Ballısaray', 'Bekdemirler',
    'Çakmak', 'Çamoğlu', 'Çatalsöğüt',
    'Dedebali', 'Delicegüney', 'Dutluca',
    'Ece',
    'Gediköiren', 'Gökçeler', 'Gülözü',
    'Harmancık Akalan', 'Hopandanişment',
    'Ilıcaksu', 'İshaklar',
    'Karaca', 'Kepekdere', 'Kılavuzlar', 'Kışmanlar', 'Kocapınar', 'Kozluca',
    'Merkez',
    'Nalbant',
    'Okçular',
    'Saçaklı',
    'Yayabaşı', 'Yeşilyurt',
  ],
  'Keles': [
    'Akçapınar', 'Alpağut', 'Avdan',
    'Baraklı', 'Başak', 'Belenören', 'Bıyıklıalanı',
    'Cuma', 'Çukur',
    'Dağ Demirciler', 'Dağdıbı', 'Davutlar', 'Dedeler', 'Delice', 'Denizler', 'Durak', 'Düvenli',
    'Epçeler', 'Ertuğrulgazi',
    'Gelemiç', 'Gököz',
    'Harmanalanı', 'Harmancık Demirci', 'Haydar', 'Hereke',
    'Issızören',
    'Karaardıç', 'Kemaliye', 'Kıran Işıklar', 'Kirazlı', 'Koca Kovacık', 'Kozbudaklar', 'Küçük Kovacık',
    'Menteşe',
    'Pınarcık',
    'Sofular', 'Sorgun',
    'Uzunöz',
    'Yağcılar', 'Yazıbaşı', 'Yenice', 'Yunuslar',
  ],
  'Orhaneli': [
    '300 Evler', 'Ağaçhisar', 'Akalan', 'Akçabük', 'Altıntaş', 'Argın',
    'Balıoğlu', 'Başköy', 'Belenoluk',
    'Celepler', 'Çatak', 'Çeki', 'Çınarcık', 'Çivili', 'Çöreler',
    'Dağgüney', 'Deliballılar', 'Demirci', 'Dere', 'Dündar',
    'Emir', 'Erenler', 'Esentepe', 'Eskidanişment',
    'Fadıl', 'Fevzipaşa', 'Firoz',
    'Gazioluk', 'Gazipaşa', 'Girencik', 'Göktepe', 'Göynükbelen', 'Gümüşpınar',
    'İkizoluk', 'İsmetpaşa',
    'Kabaklar', 'Kadı', 'Karabekirpaşa', 'Karaoğlanlar', 'Karası', 'Karıncalı', 'Koçu', 'Kusumlar', 'Küçükorhan',
    'Letafet',
    'Mahaller',
    'Nalınlar',
    'Orta',
    'Sadağı', 'Semerci', 'Serçeler', 'Sırıl', 'Söğüt', 'Süleymanbey', 'Şükriye',
    'Tepecik', 'Topuk',
    'Yakuplar', 'Yenidanişment', 'Yeşiller', 'Yörükler',
  ],
};

// ─── Antalya Mahalleler (19 ilçe) ────────────────────

export const ANTALYA_NEIGHBORHOODS: Record<string, string[]> = {
  'Akseki': [
    'Akşahap', 'Alaçeşme', 'Aşağıaşıklar', 'Bademli', 'Belenalan', 'Boğaz',
    'Bucakalan', 'Bucakkışla', 'Büyükalan', 'Ceceler', 'Cemerler', 'Cendeve',
    'Cevizli', 'Çaltılıçukur', 'Çanakpınar', 'Çınardıbi', 'Çimköy', 'Çukurköy',
    'Değirmenlik', 'Demirciler', 'Dikmen', 'Dutluca', 'Emiraşıklar', 'Erenyaka',
    'Fakılar', 'Gerişi', 'Güçlüköy', 'Gümüşdamla', 'Güneykaya', 'Günyaka',
    'Güzelsu', 'Hacı İlyas', 'Hocaköy', 'Hüsamettinköy', 'Karakışla', 'Kepez',
    'Kepezbeleni', 'Kuyucak', 'Mahmutlu', 'Menteşbey', 'Minareli', 'Pınarbaşı',
    'Sadıklar', 'Salihler', 'Sarıhacılar', 'Sarıhaliller', 'Sinanhoca',
    'Susuzşahap', 'Süleymaniye', 'Taşlıca', 'Yarpuz',
  ],
  'Aksu': [
    'Alaylı', 'Altıntaş', 'Atatürk', 'Barbaros', 'Boztepe', 'Cihadiye',
    'Cumhuriyet', 'Çalkaya', 'Çamköy', 'Dumanlar', 'Fatih', 'Fettahlı',
    'Gökdere', 'Güloluk', 'Güzelyurt', 'Hacıaliler', 'İhsaniye', 'Karaçallı',
    'Karaöz', 'Kayadibi', 'Kemerağzı', 'Konak', 'Kumköy', 'Kundu', 'Kurşunlu',
    'Macun', 'Mandırlar', 'Murtuna', 'Pınarlı', 'Soğucaksu', 'Solak',
    'Topallı', 'Yenidumanlar', 'Yeşilkaraman', 'Yurtpınar',
  ],
  'Alanya': [
    'Akçatı', 'Akdam', 'Alacami', 'Alara', 'Aliefendi', 'Asmaca', 'Avsallar',
    'Bademağacı', 'Basırlı', 'Başköy', 'Bayır', 'Bayırkozağacı', 'Bektaş',
    'Beldibi', 'Beyreli', 'Bıçakçı', 'Bucak', 'Burçaklar', 'Büyükhasbahçe',
    'Büyükpınar', 'Cikcilli', 'Cumhuriyet', 'Çakallar', 'Çamlıca', 'Çarşı',
    'Çıplaklı', 'Değirmendere', 'Demirtaş', 'Dere', 'Dinek', 'Elikesik',
    'Emişbeleni', 'Fakırcalı', 'Fığla', 'Gözübüyük', 'Gözüküçüklü',
    'Güller Pınarı', 'Gümüşgöze', 'Gümüşkavak', 'Güney', 'Güzelbağ', 'Hacet',
    'Hacıkerimler', 'Hacımehmetli', 'Hisariçi', 'Hocalar', 'İmamlı', 'İncekum',
    'İsbatlı', 'İshaklı', 'Kadıpaşa', 'Karakocalı', 'Karamanlar', 'Karapınar',
    'Kargıcak', 'Kayabaşı', 'Kestel', 'Keşefli', 'Kızılcaşehir', 'Kızlar Pınarı',
    'Kocaoğlanlı', 'Konaklı', 'Kuzyaka', 'Küçükhasbahçe', 'Mahmutlar',
    'Mahmutşeydi', 'Oba', 'Obaalacami', 'Okurcalar', 'Orhan', 'Öteköy', 'Özvadi',
    'Paşaköy', 'Payallar', 'Saburlar', 'Sapadere', 'Saray', 'Seki', 'Soğukpınar',
    'Sugözü', 'Süleymanlar', 'Şekerhane', 'Şıhlar', 'Taşbaşı', 'Tepe', 'Tırılar',
    'Tophane', 'Toslak', 'Tosmur', 'Türkler', 'Türktaş', 'Uğrak', 'Uğurlu',
    'Uzunöz', 'Üzümlü', 'Yalçı', 'Yasirali', 'Yaylakonak', 'Yaylalı', 'Yenice',
    'Yeniköy', 'Yeşilöz',
  ],
  'Demre': [
    'Alakent', 'Belören', 'Beymelek', 'Büyükkum', 'Çağman', 'Çevreli', 'Davazlar',
    'Gökyazı', 'Gürses', 'Kaleüçağız', 'Kapaklı', 'Karabucak', 'Kayaaltı',
    'Köşkerler', 'Küçükkum', 'Yavu', 'Yaylakaya',
  ],
  'Döşemealtı': [
    'Ahırtaş', 'Akkoç', 'Altınkale', 'Aşağıoba', 'Ayanlar', 'Aydınlar',
    'Bademağacı', 'Bahçeyaka', 'Bıyıklı', 'Camili', 'Çığlık', 'Çıplaklı',
    'Dağbeli', 'Dereli', 'Düzlerçamı', 'Ekşili', 'Ilıcaköy', 'Karaman',
    'Karataş', 'Karaveliler', 'Kevşirler', 'Killik', 'Kovanlık', 'Kömürcüler',
    'Nebiler', 'Orta', 'Selimiye', 'Tomalar', 'Yağca', 'Yalınlı', 'Yeniköy',
    'Yeşilbayır',
  ],
  'Elmalı': [
    'Afşar', 'Ahatlı', 'Akçaeniş', 'Akçay', 'Armutlu', 'Bayındır', 'Bayralar',
    'Beyler', 'Bozhüyük', 'Büyüksöğle', 'Camiatik', 'Camicedit', 'Çaybaşı',
    'Çobanisa', 'Çukurelma', 'Dereköy', 'Düden', 'Eskihisar', 'Eymir', 'Geçit',
    'Geçmen', 'Gökpınar', 'Göltarla', 'Gümüşyaka', 'Gündoğan', 'Hacımusalar',
    'Hacıyusuflar', 'İlyağı', 'İmircik', 'İplik Pazarı', 'İslamlar', 'Kapmescit',
    'Karaköy', 'Karamık', 'Karyağdı', 'Kışla', 'Kızılca', 'Kocapınar', 'Kuzköy',
    'Küçüksöğle', 'Macun', 'Mursal', 'Müren', 'Ovacık', 'Özdemir', 'Pirhasanlar',
    'Salur', 'Sarılar', 'Tahtamescit', 'Tavullar', 'Tekke', 'Toklular',
    'Yakaçiftlikköyü', 'Yalnızdam', 'Yapraklı', 'Yeni', 'Yılmazlı', 'Yörenler',
    'Yuva', 'Zümrütova',
  ],
  'Finike': [
    'Akçaalan', 'Alacadağ', 'Arif', 'Asarönü', 'Boldağ', 'Çamlıbel', 'Dağbağ',
    'Ernez', 'Eski', 'Gökbük', 'Gökçeyaka', 'Hasyurt', 'İskele', 'Kale',
    'Karşıyaka', 'Kızılca', 'Kum', 'Sahilkent', 'Saklısu', 'Turunçova', 'Yalnız',
    'Yazır', 'Yeni', 'Yeşilköy', 'Yeşilyurt', 'Yuvalı',
  ],
  'Gazipaşa': [
    'Akoluk', 'Aydın', 'Aydıncık', 'Bakılar', 'Beyobası', 'Beyrebucak',
    'Cumhuriyet', 'Çakmak', 'Çalıpınar', 'Çamlıca', 'Çığlık', 'Çile', 'Çimenbağ',
    'Çobanlar', 'Çörüş', 'Doğanca', 'Ekmel', 'Esenpınar', 'Esentepe', 'Gazi',
    'Göçük', 'Gökçebelen', 'Gökçesaray', 'Güneyköy', 'Gürçam', 'Hasdere', 'Ilıca',
    'İnal', 'İnceğiz', 'İstiklal', 'Kahyalar', 'Karaçukur', 'Karalar', 'Karatepe',
    'Kırahmetler', 'Kızılgüney', 'Koru', 'Korubaşı', 'Küçüklü', 'Macar',
    'Muzkent', 'Öznurtepe', 'Pazarcı', 'Sarıağaç', 'Sugözü', 'Şahinler',
    'Üçkonak', 'Yakacık', 'Yeni', 'Yenigüney', 'Yeniköy', 'Yeşilyurt',
    'Zeytinada',
  ],
  'Gündoğmuş': [
    'Akyar', 'Balkaya', 'Bedan', 'Çaltı', 'Çamlıalan', 'Çayırözü', 'Çiçekoluk',
    'Eskibağ', 'Fatih', 'Güneycik', 'Güneyyaka', 'Kalecik', 'Karabul', 'Karadere',
    'Karaisa', 'Karaköy', 'Kayabükü', 'Kozağacı', 'Köprülü', 'Narağacı',
    'Ortakonuş', 'Ortaköy', 'Özügür', 'Pembelik', 'Rasih Kaplan', 'Senir',
    'Serinyaka', 'Umutlu', 'Yeniköy',
  ],
  'İbradı': [
    'Aşağı', 'Aydınyayla', 'Başlar', 'Çukurviran', 'Düzlen', 'Ormana', 'Ürünlü',
    'Üzümdere', 'Yukarı',
  ],
  'Kaş': [
    'Ağullu', 'Ahatlı', 'Aklar', 'Akörü', 'Andifli', 'Bayındır', 'Beldibi',
    'Belenli', 'Belkonak', 'Bezirgan', 'Cemre', 'Çamlıköy', 'Çamlıova',
    'Çataloluk', 'Çavdır', 'Çayköy', 'Çerler', 'Çeşme', 'Çukurbağ', 'Dere',
    'Dirgenler', 'Doğantaş', 'Gelemiş', 'Gökçeören', 'Gökçeyazı', 'Gömbe',
    'Gürsu', 'Hacıoğlan', 'İkizce', 'İslamlar', 'Kalkan', 'Karadağ', 'Kasaba',
    'Kemer', 'Kınık', 'Kızılağaç', 'Ortabağ', 'Ova', 'Palamut', 'Pınarbaşı',
    'Sahil Barak', 'Sahilkılınçlı', 'Sarıbelen', 'Sarılar', 'Sinneli', 'Sütleğen',
    'Uğrar', 'Üzümlü', 'Yaylakılınçlı', 'Yaylapalamut', 'Yeniköy', 'Yeşilbarak',
    'Yeşilköy', 'Yuvacık',
  ],
  'Kemer': [
    'Arslanbucak', 'Beldibi', 'Beycik', 'Çamyuva', 'Göynük', 'Kiriş', 'Kuzdere',
    'Merkez', 'Ovacık', 'Tekirova', 'Ulupınar', 'Yeni',
  ],
  'Kepez': [
    'Ahatlı', 'Aktoprak', 'Altıayak', 'Altınova Düden', 'Altınova Orta',
    'Altınova Sinan', 'Atatürk', 'Avni Tolunay', 'Ayanoğlu', 'Aydoğmuş', 'Baraj',
    'Barış', 'Başköy', 'Beşkonaklılar', 'Çamlıbel', 'Çamlıca', 'Çankaya',
    'Demirel', 'Duacı', 'Duraliler', 'Düdenbaşı', 'Emek', 'Erenköy', 'Esentepe',
    'Fabrikalar', 'Fatih', 'Fevzi Çakmak', 'Gazi', 'Gaziler', 'Göçerler', 'Göksu',
    'Gülveren', 'Gündoğdu', 'Güneş', 'Habibler', 'Hüsnü Karakaş', 'Kanal',
    'Karşıyaka', 'Kazım Karabekir', 'Kepez', 'Kızıllı', 'Kirişçiler', 'Kuzeyyaka',
    'Kültür', 'Kütükçü', 'Mehmet Akif Ersoy', 'Menderes', 'Odabaşı', 'Özgürlük',
    'Santral', 'Sütçüler', 'Şafak', 'Şelale', 'Teomanpaşa', 'Ulus', 'Ünsal',
    'Varsak Esentepe', 'Varsak Karşıyaka', 'Varsak Menderes', 'Yavuz Selim',
    'Yeni', 'Yeni Doğan', 'Yeni Emek', 'Yeşiltepe', 'Yeşilyurt', 'Yükseliş',
    'Zafer', 'Zeytinlik',
  ],
  'Konyaaltı': [
    'Akdamlar', 'Akkuyu', 'Altınkum', 'Arapsuyu', 'Aşağıkaraman', 'Aydınlık',
    'Bahtili', 'Çağlarca', 'Çakırlar', 'Çitdibi', 'Demircilik', 'Doyran',
    'Doyran Çamlıbel', 'Doyran Dağ', 'Geyikbayırı', 'Gökçam', 'Gökdere', 'Gürsu',
    'Hacısekililer', 'Hisarçandır', 'Hurma', 'Karatepe', 'Kır', 'Kuruçay',
    'Kuşkavağı', 'Liman', 'Molla Yusuf', 'Öğretmenevleri', 'Pınarbaşı', 'Sarısu',
    'Siteler', 'Suiçecek', 'Toros', 'Uluç', 'Uncalı', 'Üçoluk', 'Yarbaşçandır',
    'Yeni', 'Zümrüt',
  ],
  'Korkuteli': [
    'Akyar', 'Alaaddin', 'Aşağıpazar', 'Avdan', 'Bahçeyaka', 'Bayat',
    'Bayatbademleri', 'Beğiş', 'Bozova', 'Büyükköy', 'Çaykenarı', 'Çıvgalar',
    'Çomaklı', 'Çukurca', 'Dereköy', 'Duraliler', 'Esenyurt', 'Garipce',
    'Göçerler', 'Güzle', 'İmecik', 'İmrahor', 'Karabayır', 'Karakuyu', 'Karataş',
    'Kargalık', 'Kargın', 'Karşıyaka', 'Kayabaş', 'Kemerağzı', 'Kevzer',
    'Kırkpınar', 'Kızılaliler', 'Kızılcadağ', 'Kiremitli', 'Kozağacı', 'Köseler',
    'Küçükköy', 'Küçüklü', 'Leylek', 'Mamatlar', 'Manay', 'Nebiler',
    'Osmankalfalar', 'Sımandır', 'Söğütcük', 'Sülekler', 'Taşkesiği', 'Tatköy',
    'Uzunoluk', 'Yakaköy', 'Yazır', 'Yeleme', 'Yelten', 'Yeni', 'Yeşiloba',
    'Yeşilyayla', 'Yukarıkaraman',
  ],
  'Kumluca': [
    'Adrasan', 'Altınyaka', 'Bağlık', 'Belen', 'Beşikçi', 'Beykonak',
    'Büyükalan', 'Cumhuriyet', 'Çaltı', 'Çayıçi', 'Dereköy', 'Ellinci Yıl',
    'Erentepe', 'Eskicami', 'Göksu', 'Gölcük', 'Güzören', 'Hacıveliler',
    'Hızırkahya', 'İncircik', 'Karacaağaç', 'Karacaören', 'Karşıyaka',
    'Kasapçayırı', 'Kavakköy', 'Kum', 'Kuzca', 'Mavikent', 'Merkez', 'Meydan',
    'Narenciye', 'Ortaköy', 'Salur', 'Sarıcasu', 'Sarıkavak', 'Temel Eğitim',
    'Toptaş', 'Yazır', 'Yeni', 'Yenikışla', 'Yeşilköy',
  ],
  'Manavgat': [
    'Aşağı Hisar', 'Aşağı Pazarcı', 'Ahmetler', 'Aksaz', 'Altınkaya',
    'Aşağıışıklar', 'Aydınevler', 'Bahçelievler', 'Ballıbucak', 'Belenobası',
    'Bereket', 'Beşkonak', 'Beydiğin', 'Boztepe', 'Bucakşeyhler', 'Burmahan',
    'Büklüce', 'Cevizler', 'Çağlayan', 'Çakış', 'Çaltepe', 'Çardakköy',
    'Çavuşköy', 'Çayyazı', 'Çeltiğçi', 'Çenger', 'Çolaklı', 'Değirmençözü',
    'Demirciler', 'Denizkent', 'Denizyaka', 'Dikmen', 'Doğançam', 'Dolbazlar',
    'Düzağaç', 'Emek', 'Eski Hisar', 'Evrenler Yavşı', 'Evrenseki', 'Gaziler',
    'Gebece', 'Gençler', 'Gültepe', 'Gündoğdu', 'Güzelyalı', 'Hacıali',
    'Hacıisalı', 'Hacıobası', 'Halitağalar', 'Hatipler', 'Hocalar', 'Hocalı',
    'Ilıca', 'Kadılar', 'Kalemler', 'Karabucak', 'Karabük', 'Karacalar',
    'Karakaya', 'Karaöz', 'Karavca', 'Kasaplar', 'Kavaklı', 'Kırkkavak',
    'Kısalar', 'Kızılağaç', 'Kızıldağ', 'Kızılot', 'Milli Egemenlik',
    'Mimar Sinan', 'Namaraş', 'Odaönü', 'Oymapınar', 'Örenşehir', 'Örnek',
    'Perakende', 'Sağırın', 'Salkım Evler', 'Salur', 'Sanayi', 'Saraçlı',
    'Sarılar', 'Sevinçköy', 'Seydiler', 'Sırtköy', 'Side', 'Sorgun', 'Sülek',
    'Şelale', 'Şişeler', 'Taşağıl', 'Taşkesiği', 'Tepeköy', 'Tilkiler',
    'Ulukapı', 'Uzunkale', 'Uzunlar', 'Yukarı Hisar', 'Yukarı Pazarcı',
    'Yalçıdıbi', 'Yavrudoğan', 'Yayla', 'Yaylaalan', 'Yeniköy', 'Yeşilbağ',
    'Yukarıışıklar',
  ],
  'Muratpaşa': [
    'Altındağ', 'Bahçelievler', 'Balbey', 'Barbaros', 'Bayındır', 'Cumhuriyet',
    'Çağlayan', 'Çaybaşı', 'Demircikara', 'Deniz', 'Doğuyaka', 'Dutlubahçe',
    'Elmalı', 'Ermenek', 'Etiler', 'Fener', 'Gebizli', 'Gençlik', 'Güvenlik',
    'Güzelbağ', 'Güzeloba', 'Güzeloluk', 'Haşimişcan', 'Kılınçarslan', 'Kırcami',
    'Kışla', 'Kızılarık', 'Kızılsaray', 'Kızıltoprak', 'Konuksever', 'Mehmetçik',
    'Meltem', 'Memurevleri', 'Meydankavağı', 'Muratpaşa', 'Sedir', 'Selçuk',
    'Sinan', 'Soğuksu', 'Şirinyalı', 'Tahılpazarı', 'Tarım', 'Topçular',
    'Tuzcular', 'Üçgen', 'Varlık', 'Yenigöl', 'Yenigün', 'Yeşilbahçe',
    'Yeşildere', 'Yeşilova', 'Yıldız', 'Yüksekalan', 'Zerdalilik', 'Zümrütova',
  ],
  'Serik': [
    'Abdurrahmanlar', 'Akbaş', 'Akçaalan', 'Akçapınar', 'Alacami', 'Aşağıçatma',
    'Aşağıkocayatak', 'Aşağıoba', 'Belek', 'Belkıs', 'Belpınar', 'Berendi',
    'Bilginler', 'Boğazkent', 'Bozdoğan', 'Bucakköy', 'Burmahancı', 'Büğüş',
    'Cumalı', 'Cumhuriyet', 'Çakallık', 'Çanakçı', 'Çandır', 'Çatallar',
    'Demirciler', 'Deniztepesi', 'Dikmen', 'Dorumlar', 'Eminceler', 'Eskiyürük',
    'Etler', 'Gebiz', 'Gedik', 'Gökçepınar', 'Hacıosmanlar', 'Hasdümen',
    'Haskızılören', 'Haspınar', 'Kadriye', 'Karadayı', 'Karataş', 'Karıncalı',
    'Kayaburnu', 'Kırbaş', 'Kozağacı', 'Kozan', 'Kökez', 'Kuşlar', 'Kürüş',
    'Merkez', 'Nebiler', 'Orta', 'Pınarcık', 'Sarıabalı', 'Şatırlı', 'Tekke',
    'Töngüşlü', 'Üründü', 'Yanköy', 'Yeni', 'Yeşilvadi', 'Yeşilyurt',
    'Yukarıçatma', 'Yukarıkocayatak', 'Yumaklar', 'Zırlankaya',
  ],
};

// ─── Kocaeli Mahalleler (12 ilçe) ───────────────────

export const KOCAELI_NEIGHBORHOODS: Record<string, string[]> = {
  'Başiskele': [
    'Aksiğin', 'Altınkent', 'Atakent', 'Aydınkent', 'Bahçecik Kılıçaslan', 'Bahçecik Şehitekrem',
    'Barbaros', 'Camidüzü', 'Damlar', 'Doğantepe', 'Döngel', 'Fatih', 'Havuzlubahçe',
    'Karadenizliler', 'Karşıyaka', 'Kazandere', 'Körfez', 'Kullar Merkez', 'Kullar Tepecik',
    'Kullar Yakacık', 'Mahmutpaşa', 'Ovacık', 'Paşadağ', 'Sahil', 'Sepetlipınar', 'Serdar',
    'Serindere', 'Servetiye Camı', 'Servetiye Karşı', 'Seymen', 'Tepecik', 'Vezirçiftliği',
    'Yaylacık', 'Yeniköy Merkez', 'Yeşilkent', 'Yeşilyurt', 'Yuvacık Yakacık',
  ],
  'Çayırova': [
    'Akse', 'Atatürk', 'Cumhuriyet', 'Çayırova', 'Emek', 'İnönü', 'Özgürlük', 'Şekerpınar', 'Yeni',
  ],
  'Darıca': [
    'Abdi İpekçi', 'Bağlarbaşı', 'Bayramoğlu', 'Cami', 'Emek', 'Fevzi Çakmak',
    'Kazım Karabekir', 'Nene Hatun', 'Osmangazi', 'Piri Reis', 'Sırasöğütler',
    'Yalı', 'Yeni', 'Zincirlikuyu',
  ],
  'Derince': [
    'Çavuşlu', 'Çenedağ', 'Çınarlı', 'Deniz', 'Dumlupınar', 'Fatih Sultan', 'Geredeli',
    'İbni Sina', 'Karagöllü', 'Kaşıkçı', 'Mersincik', 'Sırrıpaşa', 'Tahtalı',
    'Terziler', 'Toylar', 'Yavuz Sultan', 'Yenikent',
  ],
  'Dilovası': [
    'Cumhuriyet', 'Çerkeşli', 'Demirciler', 'Diliskelesi', 'Fatih', 'Kayapınar',
    'Köseler', 'Mimar Sinan', 'Orhangazi', 'Tavşancıl', 'Tepecik', 'Turgut Özal',
  ],
  'Gebze': [
    'Adem Yavuz', 'Ahatlı', 'Arapçeşme', 'Balçık', 'Barış', 'Beylikbağı', 'Cumaköy',
    'Cumhuriyet', 'Denizli', 'Duraklı', 'Elbizli', 'Eskihisar', 'Gaziler', 'Güzeller',
    'Hacıhalil', 'Hatipler', 'Hürriyet', 'İnönü', 'İstasyon', 'Kadıllı', 'Kargalı',
    'Kirazpınar', 'Köşklüçeşme', 'Mevlana', 'Mimar Sinan', 'Mollafenari', 'Muallimköy',
    'Mudarlı', 'Mustafapaşa', 'Osman Yılmaz', 'Ovacık', 'Pelitli', 'Sultan Orhan',
    'Tatlıkuyu', 'Tavşanlı', 'Tepemanayır', 'Ulus', 'Yağcılar', 'Yavuz Selim', 'Yenikent',
  ],
  'Gölcük': [
    'Atatürk', 'Ayvazpınarı', 'Cumhuriyet', 'Çiftlik', 'Değirmendere Merkez',
    'Değirmendere Yalı', 'Deniz Evler', 'Donanma', 'Dumlupınar', 'Düzağaç',
    'Eskiferhadiye', 'Ferhadiye', 'Halidere Yalı', 'Halidere Yeni', 'Hamidiye',
    'Hasaneyn', 'Hisareyn Merkez', 'İcadiye', 'İhsaniye Merkez', 'İpek Yolu',
    'İrşadiye', 'Karaköprü', 'Kavaklı', 'Körfez', 'Lütfiye', 'Mamuriye', 'Merkez',
    'Mesruriye', 'Nimetiye', 'Nüzhetiye', 'Örcün', 'Panayır', 'Piyalepaşa',
    'Saraylı', 'Selimiye', 'Siyretiye', 'Sofular', 'Şehitler', 'Şevketiye',
    'Şirinköy', 'Topçular', 'Ulaşlı Yalı', 'Ulaşlı Yavuz Sultan Selim', 'Ümmiye',
    'Yazlık Merkez', 'Yazlık Yeni', 'Yeni', 'Yukarı', 'Yunus Emre', 'Yüzbaşılar',
  ],
  'İzmit': [
    '28 Haziran', 'Akarca', 'Akçakoca', 'Akmeşe Atatürk', 'Akmeşe Cumhuriyet', 'Akpınar',
    'Alikahya Atatürk', 'Alikahya Cumhuriyet', 'Alikahya Fatih', 'Alikahya Merkez',
    'Ambarcı', 'Arızlı', 'Arpalık İhsaniye', 'Ayazma', 'Bağlıca', 'Balören', 'Bayraktar',
    'Bekirdere', 'Biberoğlu', 'Böğürgen', 'Bulduk', 'Cedit', 'Cumhuriyet', 'Çağırgan',
    'Çavuşoğlu', 'Çayırköy', 'Çubuklu Bala', 'Çubuklu Osmaniye', 'Çukurbağ', 'Dağköy',
    'Doğan', 'Durhasan', 'Düğmeciler', 'Emirhan', 'Erenler', 'Eseler', 'Fatih', 'Fethiye',
    'Fevzi Çakmak', 'Gedikli', 'Gökçeören', 'Gülbahçe Kadriye', 'Gültepe', 'Gündoğdu',
    'Güvercinlik', 'Hacıhasan', 'Hacıhızır', 'Hakaniye', 'Hasancıklar', 'Hatipköy',
    'Kabaoğlu', 'Kadıköy', 'Karaabdülbaki', 'Karabaş', 'Karadenizliler', 'Kaynarca',
    'Kemalpaşa', 'Kısalar', 'Kocatepe', 'Kozluca', 'Kozluk', 'Körfez', 'Kulfallı',
    'Kulmahmut', 'Kurtdere', 'Kuruçeşme Fatih', 'M. Alipaşa', 'Malta', 'Mecidiye',
    'Nebihoca', 'Orhan', 'Orhaniye', 'Ortaburun', 'Ömerağa', 'Sanayi', 'Sapakpınar',
    'Sarışeyh', 'Sekbanlı', 'Sepetçi', 'Serdar', 'Sultaniye', 'Süleymaniye', 'Süverler',
    'Şahinler', 'Şirintepe', 'Tavşantepe', 'Tepecik', 'Tepeköy', 'Terzibayırı',
    'Topçular', 'Turgut', 'Tüysüzler', 'Veliahmet', 'Yahyakaptan', 'Yassıbağ', 'Yeni',
    'Yenice', 'Yenidoğan', 'Yenişehir', 'Yeşilova', 'Zabitan', 'Zeytinburnu',
  ],
  'Kandıra': [
    'Ağaçağıl', 'Ahmethacilar', 'Akbal', 'Akçabeyli', 'Akçakese', 'Akçaova', 'Akdurak',
    'Akıncı', 'Alaybey', 'Alefli', 'Antaplı', 'Avdan', 'Aydınlık', 'Babaköy', 'Babalı',
    'Bağırganlı', 'Balaban', 'Balcı', 'Ballar', 'Beyce', 'Beylerbeyi', 'Bolu', 'Bozburun',
    'Cebeci', 'Çakırcaali', 'Çakmaklar', 'Çalca', 'Çalköy', 'Çalyer', 'Çamkonak', 'Çarşı',
    'Çerçili', 'Dalca', 'Deliveli', 'Doğancılı', 'Döngelli', 'Duraklı', 'Eğercili',
    'Elmacık', 'Esentepe', 'Ferizli', 'Gebeşler', 'Goncaaydın', 'Hacılar', 'Hacımazlı',
    'Hacışeyh', 'Hediyeli', 'Hıdırlar', 'Hüdaverdiler', 'İncecik', 'Kabaağaç', 'Kanatlar',
    'Karaağaç', 'Karadivan', 'Karlı', 'Kaymaz', 'Kaymaz Erikli', 'Kefken', 'Kerpe',
    'Kırkarmut', 'Kızılçapınar', 'Kocakaymaz', 'Kubuzcu', 'Kurtyeri', 'Lokmanlı',
    'Mancırlar', 'Merkez Erikli', 'Mülküşehsuvar', 'Nasuhlar', 'Orhan', 'Ömerli', 'Özbey',
    'Pelitpınarı', 'Pınardüzü', 'Pınarlı', 'Pirceler', 'Safalı', 'Sarıahmetler',
    'Sarıcaali', 'Sarıgazi', 'Sarnıçlar', 'Selametli', 'Selimköy', 'Sepetçi', 'Seyitaliler',
    'Sinanlıbilalli', 'Sucuali', 'Süllü', 'Şerefsungur', 'Tatarahmet', 'Teksen', 'Terziler',
    'Topluca', 'Üğümce', 'Yağcılar', 'Yusufça',
  ],
  'Karamürsel': [
    '4 Temmuz', 'Akçat', 'Akpınar', 'Avcıköy', 'Çamçukur', 'Çamdibi', 'Dereköy',
    'Ereğli', 'Fulacık', 'Hayriye', 'İhsaniye', 'İnebeyli', 'Kadriye', 'Karaahmetli',
    'Karapınar', 'Kayacık', 'Kızderbent', 'Oluklu', 'Osmaniye', 'Pazarköy', 'Safiye',
    'Semetler', 'Senaiye', 'Suludere', 'Tahtalı', 'Tepeköy', 'Yalakdere',
  ],
  'Kartepe': [
    'Acısu', 'Arslanbey', 'Ataevler', 'Ataşehir', 'Balaban', 'Çepni', 'Derbent',
    'Dumlupınar', 'Emekevler', 'Ertuğrul Gazi', 'Eşme', 'Eşme Ahmediye',
    'Fatih Sultan Mehmet', 'Havluburun', 'İbrikdere', 'İstasyon', 'Karatepe', 'Ketenciler',
    'Köseköy', 'Maşukiye', 'Nusretiye', 'Pazarçayırı', 'Rahmiye', 'Sarımeşe', 'Serinlik',
    'Suadiye', 'Sultaniye', 'Şevkatiye', 'Şirinsülhiye', 'Uzunbey', 'Uzunçiftlik', 'Uzuntarla',
  ],
  'Körfez': [
    '17 Ağustos', 'Agah Ateş', 'Alihoçalar', 'Atalar', 'Barbaros', 'Belen', 'Cuma',
    'Cumhuriyet', 'Çamlıtepe', 'Çıraklı', 'Dere', 'Dikenli', 'Elmacık', 'Esentepe',
    'Fatih', 'Güney', 'Hacı Akif', 'Hacı Osman', 'Himmetli', 'İlimtepe', 'Kalburcu',
    'Karayakuplu', 'Kışladüzü', 'Kirazlıyalı', 'Kutluca', 'Kuzey', 'Mimar Sinan',
    'Naip', 'Osmanlı', 'Sevindikli', 'Sipahiler', 'Şemsettin', 'Şirinyalı',
    'Yavuz Sultan Selim', 'Yeniyalı', 'Yukarı Hereke',
  ],
};

// ─── Muğla Mahalleler (13 ilçe) ─────────────────────

export const MUGLA_NEIGHBORHOODS: Record<string, string[]> = {
  'Bodrum': [
    'Akçaalan', 'Akyarlar', 'Bahçelievler', 'Bahçeyaka', 'Bitez', 'Cevat Şakir',
    'Cumhuriyet', 'Çamarası', 'Çamlık', 'Çarşı', 'Çırkan', 'Çiftlik', 'Çömlekçi',
    'Dağbelen', 'Dereköy', 'Dirmil', 'Eskiçeşme', 'Farılya', 'Geriş', 'Gökpınar',
    'Gölbaşı', 'Gölköy', 'Gümbet', 'Gümüşlük', 'Gündoğan', 'Gürece', 'Güvercinlik',
    'İslamhaneleri', 'Karabağ', 'Karaova', 'Kemer', 'Kızılağaç', 'Konacık', 'Koyunbaba',
    'Kumbahçe', 'Kumköy', 'Küçükbük', 'Mazıköy', 'Mumcular', 'Müskebi', 'Peksimet',
    'Pınarıbelen', 'Sazköy', 'Tepecik', 'Tepecik (Karaova)', 'Torba', 'Turgutreis',
    'Türkbükü', 'Türkkuyusu', 'Umurca', 'Yahşi', 'Yakaköy', 'Yalıkavak', 'Yeniköy',
    'Yeniköy (Karaova)', 'Yokuşbaşı',
  ],
  'Dalaman': [
    'Akçataş', 'Altıntaş', 'Atakent', 'Bezkese', 'Bozbel', 'Çöğmen', 'Darıyeri', 'Ege',
    'Elçik', 'Gürköy', 'Gürleyk', 'Hürriyet', 'Kapukargın', 'Karacaağaç', 'Karaçalı',
    'Kargınkürü', 'Kavacık', 'Kayadibi', 'Kızılkaya', 'Merkez', 'Narlı', 'Sabunlu',
    'Söğütlüyurt', 'Şerefler', 'Taşbaşı',
  ],
  'Datça': [
    'Cumalı', 'Datça', 'Emecik', 'Hızırşah', 'İskele', 'Karaköy', 'Kızlan',
    'Mesudiye', 'Reşadiye', 'Sındı', 'Yaka', 'Yazı',
  ],
  'Fethiye': [
    'Akarca', 'Babataşı', 'Bozyer', 'Camii', 'Cumhuriyet', 'Çamköy', 'Çatalarık',
    'Çenger', 'Çiftlik', 'Eldirek', 'Esenköy', 'Faralya', 'Foça', 'Göcek', 'Gökben',
    'Gökçeovacık', 'İncirköy', 'İnlice', 'Karaağaç', 'Karacaören', 'Karaçulha',
    'Karagedik', 'Karagözler', 'Karakecililer', 'Kargı', 'Kayaköy', 'Kesikkapı',
    'Kızılbel', 'Koruköy', 'Menteşeoğlu', 'Nif', 'Ölüdeniz', 'Patlangıç', 'Pazaryeri',
    'Söğütlü', 'Taşyaka', 'Tuzla', 'Yakacık', 'Yanıklar', 'Yeni', 'Yeşilüzümlü',
  ],
  'Kavaklıdere': [
    'Bakırcılar', 'Cumhuriyet', 'Çamlıbel', 'Çamlıyurt', 'Çatak', 'Çavdır', 'Çayboyu',
    'Derebağ', 'Kurucuova', 'Menteşe', 'Nebiler', 'Ortaköy', 'Salkım', 'Yeni', 'Yeşilköy',
  ],
  'Köyceğiz': [
    'Akköprü', 'Balcılar', 'Beyobası', 'Çandır', 'Çayhisar', 'Döğüşbelen', 'Ekincik',
    'Gelişim', 'Gülpınar', 'Hamitköy', 'Karaçam', 'Kavakarası', 'Köyceğiz', 'Otmanlar',
    'Pınar', 'Sazak', 'Sultaniye', 'Toparlar', 'Ulucami', 'Yangı', 'Yayla', 'Yeni',
    'Yeşilköy', 'Zaferler', 'Zeytinalanı',
  ],
  'Marmaris': [
    'Adaköy', 'Armutalan', 'Bayır', 'Beldibi', 'Bozburun', 'Camii Avlu', 'Çamdibi',
    'Çamlı', 'Çetibeli', 'Çıldır', 'Gölenye', 'Hatipirimi', 'Hisarönü', 'İçmeler',
    'Karaca', 'Karşıyaka', 'Kemeraltı', 'Orhaniye', 'Osmaniye', 'Sarıana', 'Selimiye',
    'Sinan', 'Siteler', 'Söğüt', 'Taşlıca', 'Tepe', 'Turgut', 'Turunç', 'Yeşilbelde',
    'Yeşilova',
  ],
  'Menteşe': [
    'Akçaova', 'Akkaya', 'Akyer', 'Algı', 'Avcılar', 'Balıbey', 'Bayır', 'Bozyer',
    'Camikebir', 'Çakmak', 'Çamoluk', 'Çatakbağyaka', 'Çırpı', 'Çiftlik', 'Dağdibi',
    'Dağpınar', 'Denizova', 'Derinkuyu', 'Doğan', 'Dokuzçam', 'Düğerek', 'Emirbeyazıt',
    'Esençay', 'Fadıl', 'Gazeller', 'Gevenes', 'Göktepe', 'Gülağzı', 'Günlüce',
    'Hacırüstem', 'İkizce', 'Kafaca', 'Karacaören', 'Karamehmet', 'Karşıyaka', 'Kıran',
    'Kiramettin', 'Kozağaç', 'Kötekli', 'Kuyucak', 'Kuzluk', 'Meke', 'Muratlar',
    'Muslihittin', 'Müştakbey', 'Orhaniye', 'Orta', 'Ortaköy', 'Özlüce', 'Paşapınarı',
    'Salihpaşalar', 'Sarnıç', 'Sungur', 'Şenyayla', 'Şeyh', 'Taşlı', 'Yaraş',
    'Yemişendere', 'Yenibağyaka', 'Yenice', 'Yeniköy', 'Yeniköy (Yerkesik)', 'Yerkesik',
    'Yeşilyurt', 'Yörükoğlu', 'Zeytin',
  ],
  'Milas': [
    'Ağaçlıhöyük', 'Ahmetçavuş Hayıtlı', 'Akçakaya', 'Akçalı', 'Akkovanlık', 'Akyol',
    'Alaçam', 'Alatepe', 'Aslanyaka', 'Avşar', 'Aydınlıkevler', 'Bafa', 'Bağdamları',
    'Baharlı', 'Bahçe', 'Bahçeburun', 'Balcılar', 'Bayır', 'Beçin', 'Beyciler',
    'Boğaziçi', 'Bozalan', 'Bozbük', 'Burgaz', 'Cumhuriyet', 'Çakıralan', 'Çallı',
    'Çamköy', 'Çamibelen', 'Çamlıca', 'Çamlıyurt', 'Çamovalı', 'Çandır', 'Çınarlı',
    'Çiftlik', 'Çomakdağ Kızılağaç', 'Çökertme', 'Çukur', 'Damlıboğaz', 'Danişment',
    'Demirciler', 'Dere', 'Derince', 'Dibekdere', 'Dörttepe', 'Eğridere', 'Ekinanbarı',
    'Ekindere', 'Ekizköy', 'Ekiztaş', 'Emek', 'Epçe', 'Etrenli', 'Fesleğen',
    'Firuzpaşa Gazipaşa', 'Gökbel', 'Gökçeler', 'Göldere', 'Gölyaka', 'Güllük',
    'Gümüşlük', 'Güneş', 'Günlük', 'Gürcegiz', 'Gürçamlar', 'Hacı İlyas', 'Hacıabtı',
    'Hacıahmetler', 'Hasanlar', 'Hisarbaşı Hoca Bedrettin', 'Hisarcık', 'Hüsamlar', 'İçme',
    'İsmet Paşa', 'Kafaca', 'Kalem', 'Kalınağıl', 'Kandak', 'Kapıkırı', 'Karacaağaç',
    'Karacahisar', 'Karahayıt', 'Karakuyu', 'Karapınar', 'Kargıcak', 'Karşıyaka',
    'Kayabaşı', 'Kayabükü', 'Kayadere', 'Kazıklı', 'Kemikler', 'Ketendere', 'Kılavuz',
    'Kırcağız', 'Kısırlar', 'Kıyıkışlacık', 'Kızılağaç', 'Kızılcakuyu', 'Kızılcayıkık',
    'Konak', 'Koru', 'Korucuk', 'Köşk', 'Kultak', 'Kurudere', 'Kuzyaka',
    'Küçükdibekdere', 'Menteş', 'Meşelik', 'Narhisar', 'Olukbaşı', 'Ortaköy',
    'Ovakışlacık', 'Ören', 'Pınarası', 'Pınarcık', 'Pınar', 'Sakarkaya', 'Sarıkaya',
    'Savran', 'Sek', 'Selimiye', 'Söğütçük', 'Şenköy', 'Şevketiye', 'Tuzabat',
    'Türkevleri', 'Ulaş', 'Yaka', 'Yaşyer', 'Yoğunoluk', 'Yusufça',
  ],
  'Ortaca': [
    'Akıncı', 'Arıkbaşı', 'Atatürk', 'Bahçelievler', 'Beşköprü', 'Cumhuriyet', 'Çaylı',
    'Dalaklı', 'Dalyan', 'Dereköy', 'Dikmekavak', 'Ekşiliyurt', 'Eskiköy', 'Fevziye',
    'Gökbel', 'Gölbaşı', 'Güzelyurt', 'Karaburun', 'Karadonlar', 'Kemaliye', 'Mergenli',
    'Okçular', 'Sarıgerme', 'Tepearası', 'Terzialiler', 'Yerbelen', 'Yeşilyurt',
  ],
  'Seydikemer': [
    'Alaçat', 'Arifler', 'Arsaköy', 'Atlıdere', 'Bağlıağaç', 'Bayırköy', 'Bekçiler',
    'Belen', 'Boğalar', 'Boğaziçi', 'Ceylan', 'Cumhuriyet', 'Çaltılar', 'Çaltıözü',
    'Çamurköy', 'Çatak', 'Çayan', 'Çaykenarı', 'Çobanisa', 'Çobanlar', 'Çökek',
    'Çukurincir', 'Demirler', 'Dereköy', 'Dodurga', 'Doğanlar', 'Dont', 'Döğer', 'Eşen',
    'Gerişburnu', 'Girmeler', 'Gölbent', 'Güneşli', 'Hacıosmanlar', 'İzzettinköy',
    'Kabaağaç', 'Kadıköy', 'Karadere', 'Karaköy', 'Kayabaşı', 'Kayacık', 'Kayadibi',
    'Kıncılar', 'Kınık', 'Korubükü', 'Kumluova', 'Menekşe', 'Minare', 'Ortaköy', 'Ören',
    'Paşalı', 'Sahilceylan', 'Sarıyer', 'Seki', 'Seydiler', 'Söğütlüdere', 'Temel',
    'Uğurlu', 'Yakabağ', 'Yakaköy', 'Yayla Eldirek', 'Yayla Gökben', 'Yayla Karaçulha',
    'Yayla Patlangıç', 'Zorlar',
  ],
  'Ula': [
    'Akçapınar', 'Akyaka', 'Alparslan', 'Arıcılar', 'Armutçuk', 'Ataköy', 'Ayazkıyı',
    'Çıtlık', 'Çiçekli', 'Çörüş', 'Demirtaş', 'Elmalı', 'Esentepe', 'Gökçe', 'Gökova',
    'Gölcük', 'Karabörtlen', 'Kavakçalı', 'Kira', 'Kızılağaç', 'Kızılyaka', 'Köprübaşı',
    'Örnekköy', 'Portalık', 'Sarayyani', 'Şirinköy', 'Turgut', 'Yaylasöğüt', 'Yeşilçam',
    'Yeşilova',
  ],
  'Yatağan': [
    'Akgedik', 'Akyol', 'Alaşar', 'Atatürk', 'Bağyaka', 'Bahçeyaka', 'Bencik', 'Bozarmut',
    'Bozüyük', 'Cazkırlar', 'Cumhuriyet', 'Çakırlar', 'Çamlıca', 'Çukuröz', 'Dere',
    'Deştin', 'Doğanköy', 'Elmacık', 'Esenköy', 'Eskihisar', 'Gökgedik', 'Gökpınar',
    'Hacıbayramlar', 'Hacıveliler', 'Hisarardı', 'Kadıköy', 'Kafaca Kaplancık', 'Kapubağ',
    'Katrancı', 'Kavak', 'Kırıkköy', 'Konak', 'Kozağaç', 'Köklük', 'Madenler', 'Mesken',
    'Nebiköy', 'Şahinler', 'Şeref', 'Turgut', 'Turgutlar', 'Yava', 'Yayla', 'Yeni',
    'Yenikarakuyu', 'Yeniköy', 'Yeşilbağcılar', 'Yeşilköy', 'Yukarıyayla', 'Zeytinköy',
  ],
};

export function getDistrictsForCity(city: string): string[] {
  return CITY_DISTRICTS[city] ?? CITY_DISTRICTS['İstanbul'];
}

export function getNeighborhoodsForDistrict(city: string, district: string): string[] {
  if (city === 'İstanbul') return DISTRICT_NEIGHBORHOODS[district] ?? [];
  if (city === 'Ankara') return ANKARA_NEIGHBORHOODS[district] ?? [];
  if (city === 'İzmir') return IZMIR_NEIGHBORHOODS[district] ?? [];
  if (city === 'Bursa') return BURSA_NEIGHBORHOODS[district] ?? [];
  if (city === 'Kocaeli') return KOCAELI_NEIGHBORHOODS[district] ?? [];
  if (city === 'Muğla') return MUGLA_NEIGHBORHOODS[district] ?? [];
  if (city === 'Antalya') return ANTALYA_NEIGHBORHOODS[district] ?? [];
  return [];
}

// Tüm mahalleler - arama için düz liste
export function getAllNeighborhoods(city: string): { district: string; neighborhood: string }[] {
  const districts = getDistrictsForCity(city);
  const result: { district: string; neighborhood: string }[] = [];
  for (const district of districts) {
    const neighborhoods = getNeighborhoodsForDistrict(city, district);
    for (const neighborhood of neighborhoods) {
      result.push({ district, neighborhood });
    }
  }
  return result;
}

// ─── İşlem Tipleri ────────────────────────────────────

export const TRANSACTION_TYPES: { key: TransactionType; label: string }[] = [
  { key: 'SALE', label: 'Satılık' },
  { key: 'RENT', label: 'Kiralık' },
];

// ─── Mülk Tipleri ─────────────────────────────────────

export const PROPERTY_TYPES: { key: PropertyType; label: string }[] = [
  { key: 'RESIDENTIAL', label: 'Konut' },
  { key: 'COMMERCIAL', label: 'Ticari' },
  { key: 'LAND', label: 'Arsa' },
  { key: 'URBAN_RENEWAL', label: 'Kentsel Dönüşüm' },
];

// ─── Oda Sayıları ─────────────────────────────────────

export const ROOM_OPTIONS = [
  'Stüdyo', '1+0', '1+1', '2+0', '2+1', '3+1', '3+2', '4+1', '4+2', '5+1', '5+2', '6+',
];

// ─── Isıtma Tipleri ───────────────────────────────────

export const HEATING_TYPES = [
  'Doğalgaz (Kombi)', 'Doğalgaz (Kat Kalörifer)', 'Merkezi Sistem',
  'Soba', 'Klima', 'Yerden Isıtma', 'Yok',
];

// ─── Bina Yaşı Aralıkları ─────────────────────────────

export const BUILDING_AGE_OPTIONS = [
  { key: '0', label: '0 (Sıfır Bina)' },
  { key: '1-5', label: '1 - 5' },
  { key: '6-10', label: '6 - 10' },
  { key: '11-15', label: '11 - 15' },
  { key: '16-20', label: '16 - 20' },
  { key: '21-25', label: '21 - 25' },
  { key: '26-30', label: '26 - 30' },
  { key: '31+', label: '31 ve üzeri' },
];
