// Deprem Bölgeleri — AFAD 2018 Türkiye Deprem Tehlike Haritası
// Kaynak: deprem.afad.gov.tr
// Son güncelleme: Temmuz 2026

export type EarthquakeZone = 1 | 2 | 3 | 4 | 5;

export const EARTHQUAKE_ZONES: Record<string, Record<string, EarthquakeZone>> = {
  'İstanbul': {
    'Adalar': 1,
    'Arnavutköy': 2,
    'Ataşehir': 1,
    'Avcılar': 1,
    'Bağcılar': 1,
    'Bahçelievler': 1,
    'Bakırköy': 1,
    'Başakşehir': 1,
    'Bayrampaşa': 1,
    'Beşiktaş': 1,
    'Beykoz': 1,
    'Beylikdüzü': 1,
    'Beyoğlu': 1,
    'Büyükçekmece': 1,
    'Çatalca': 2,
    'Çekmeköy': 2,
    'Esenler': 1,
    'Esenyurt': 1,
    'Eyüpsultan': 1,
    'Fatih': 1,
    'Gaziosmanpaşa': 1,
    'Güngören': 1,
    'Kadıköy': 1,
    'Kağıthane': 1,
    'Kartal': 1,
    'Küçükçekmece': 1,
    'Maltepe': 1,
    'Pendik': 1,
    'Sancaktepe': 1,
    'Sarıyer': 1,
    'Silivri': 1,
    'Sultanbeyli': 1,
    'Sultangazi': 1,
    'Şile': 2,
    'Şişli': 1,
    'Tuzla': 1,
    'Ümraniye': 1,
    'Üsküdar': 1,
    'Zeytinburnu': 1,
  },
  'Ankara': {
    'Akyurt': 3,
    'Altındağ': 3,
    'Ayaş': 3,
    'Bala': 4,
    'Beypazarı': 3,
    'Çamlıdere': 2,
    'Çankaya': 3,
    'Çubuk': 3,
    'Elmadağ': 3,
    'Etimesgut': 3,
    'Evren': 4,
    'Gölbaşı': 3,
    'Güdül': 3,
    'Haymana': 4,
    'Kahramankazan': 3,
    'Kalecik': 3,
    'Keçiören': 3,
    'Kızılcahamam': 2,
    'Mamak': 3,
    'Nallıhan': 2,
    'Polatlı': 3,
    'Pursaklar': 3,
    'Sincan': 3,
    'Şereflikoçhisar': 4,
    'Yenimahalle': 3,
  },
  'İzmir': {
    'Aliağa': 1,
    'Balçova': 1,
    'Bayındır': 1,
    'Bayraklı': 1,
    'Bergama': 1,
    'Beydağ': 2,
    'Bornova': 1,
    'Buca': 1,
    'Çeşme': 1,
    'Çiğli': 1,
    'Dikili': 1,
    'Foça': 1,
    'Gaziemir': 1,
    'Güzelbahçe': 1,
    'Karabağlar': 1,
    'Karaburun': 1,
    'Karşıyaka': 1,
    'Kemalpaşa': 1,
    'Kınık': 1,
    'Kiraz': 2,
    'Konak': 1,
    'Menderes': 1,
    'Menemen': 1,
    'Narlıdere': 1,
    'Ödemiş': 2,
    'Seferihisar': 1,
    'Selçuk': 1,
    'Tire': 2,
    'Torbalı': 1,
    'Urla': 1,
  },
  'Bursa': {
    'Büyükorhan': 2,
    'Gemlik': 1,
    'Gürsu': 1,
    'Harmancık': 2,
    'İnegöl': 2,
    'İznik': 1,
    'Karacabey': 1,
    'Keles': 2,
    'Kestel': 1,
    'Mudanya': 1,
    'Mustafakemalpaşa': 2,
    'Nilüfer': 1,
    'Orhaneli': 2,
    'Orhangazi': 1,
    'Osmangazi': 1,
    'Yenişehir': 1,
    'Yıldırım': 1,
  },
  'Antalya': {
    'Akseki': 2,
    'Aksu': 2,
    'Alanya': 2,
    'Demre': 2,
    'Döşemealtı': 2,
    'Elmalı': 2,
    'Finike': 2,
    'Gazipaşa': 2,
    'Gündoğmuş': 2,
    'İbradı': 3,
    'Kaş': 1,
    'Kemer': 2,
    'Kepez': 2,
    'Konyaaltı': 2,
    'Korkuteli': 3,
    'Kumluca': 2,
    'Manavgat': 2,
    'Muratpaşa': 2,
    'Serik': 2,
  },
  'Balıkesir': {
    'Altıeylül': 2,
    'Ayvalık': 1,
    'Balya': 2,
    'Bandırma': 1,
    'Bigadiç': 2,
    'Burhaniye': 1,
    'Dursunbey': 2,
    'Edremit': 1,
    'Erdek': 1,
    'Gömeç': 1,
    'Gönen': 1,
    'Havran': 1,
    'İvrindi': 2,
    'Karesi': 2,
    'Kepsut': 2,
    'Manyas': 2,
    'Marmara': 1,
    'Savaştepe': 2,
    'Sındırgı': 2,
    'Susurluk': 2,
  },
  'Kocaeli': {
    'Başiskele': 1,
    'Çayırova': 1,
    'Darıca': 1,
    'Derince': 1,
    'Dilovası': 1,
    'Gebze': 1,
    'Gölcük': 1,
    'İzmit': 1,
    'Kandıra': 1,
    'Karamürsel': 1,
    'Kartepe': 1,
    'Körfez': 1,
  },
  'Mersin': {
    'Akdeniz': 2,
    'Anamur': 2,
    'Aydıncık': 2,
    'Bozyazı': 2,
    'Çamlıyayla': 3,
    'Erdemli': 2,
    'Gülnar': 3,
    'Mezitli': 2,
    'Mut': 3,
    'Silifke': 2,
    'Tarsus': 2,
    'Toroslar': 2,
    'Yenişehir': 2,
  },
  'Muğla': {
    'Bodrum': 1,
    'Dalaman': 1,
    'Datça': 1,
    'Fethiye': 1,
    'Kavaklıdere': 2,
    'Köyceğiz': 1,
    'Marmaris': 1,
    'Menteşe': 1,
    'Milas': 1,
    'Ortaca': 1,
    'Seydikemer': 1,
    'Ula': 1,
    'Yatağan': 2,
  },
  'Tekirdağ': {
    'Çerkezköy': 1,
    'Çorlu': 1,
    'Ergene': 1,
    'Hayrabolu': 2,
    'Kapaklı': 1,
    'Malkara': 2,
    'Marmara Ereğlisi': 1,
    'Muratlı': 2,
    'Saray': 2,
    'Süleymanpaşa': 1,
    'Şarköy': 1,
  },
  'Eskişehir': {
    'Alpu': 3,
    'Beylikova': 3,
    'Çifteler': 3,
    'Günyüzü': 3,
    'Han': 3,
    'İnönü': 2,
    'Mahmudiye': 3,
    'Mihalgazi': 2,
    'Mihalıççık': 2,
    'Odunpazarı': 2,
    'Sarıcakaya': 2,
    'Seyitgazi': 3,
    'Sivrihisar': 3,
    'Tepebaşı': 2,
  },
  'Sakarya': {
    'Adapazarı': 1,
    'Akyazı': 1,
    'Arifiye': 1,
    'Erenler': 1,
    'Ferizli': 1,
    'Geyve': 1,
    'Hendek': 1,
    'Karapürçek': 1,
    'Karasu': 1,
    'Kaynarca': 1,
    'Kocaali': 1,
    'Pamukova': 1,
    'Sapanca': 1,
    'Serdivan': 1,
    'Söğütlü': 1,
    'Taraklı': 2,
  },
  'Samsun': {
    'Alaçam': 2,
    'Asarcık': 2,
    'Atakum': 2,
    'Ayvacık': 2,
    'Bafra': 2,
    'Canik': 2,
    'Çarşamba': 2,
    'Havza': 2,
    'İlkadım': 2,
    'Kavak': 2,
    'Ladik': 2,
    'Ondokuzmayıs': 2,
    'Salıpazarı': 2,
    'Tekkeköy': 2,
    'Terme': 2,
    'Vezirköprü': 3,
    'Yakakent': 2,
  },
  'Edirne': {
    'Enez': 2,
    'Havsa': 3,
    'İpsala': 2,
    'Keşan': 2,
    'Lalapaşa': 3,
    'Meriç': 2,
    'Merkez': 2,
    'Süloğlu': 3,
    'Uzunköprü': 2,
  },
  'Kayseri': {
    'Akkışla': 3,
    'Bünyan': 3,
    'Develi': 2,
    'Felahiye': 3,
    'Hacılar': 2,
    'İncesu': 2,
    'Kocasinan': 2,
    'Melikgazi': 2,
    'Özvatan': 3,
    'Pınarbaşı': 3,
    'Sarıoğlan': 3,
    'Sarız': 2,
    'Talas': 2,
    'Tomarza': 2,
    'Yahyalı': 2,
    'Yeşilhisar': 2,
  },
  'Konya': {
    'Ahırlı': 3,
    'Akören': 3,
    'Akşehir': 2,
    'Altınekin': 4,
    'Beyşehir': 3,
    'Bozkır': 3,
    'Cihanbeyli': 4,
    'Çeltik': 3,
    'Çumra': 4,
    'Derbent': 3,
    'Derebucak': 3,
    'Doğanhisar': 3,
    'Emirgazi': 4,
    'Ereğli': 3,
    'Güneysınır': 3,
    'Hadim': 3,
    'Halkapınar': 3,
    'Hüyük': 3,
    'Ilgın': 3,
    'Kadınhanı': 3,
    'Karapınar': 4,
    'Karatay': 4,
    'Kulu': 4,
    'Meram': 3,
    'Sarayönü': 4,
    'Selçuklu': 3,
    'Seydişehir': 3,
    'Taşkent': 3,
    'Tuzlukçu': 3,
    'Yalıhüyük': 3,
    'Yunak': 3,
  },
  'Kuzey Kıbrıs': {
    'Lefkoşa': 2,
    'Gazimağusa': 2,
    'Girne': 2,
    'Güzelyurt': 2,
    'İskele': 2,
    'Lefke': 3,
  },
};

// ─── İlçe bazlı kıyı bölgesi listesi (3621 Kıyı Kanunu riski) ───
// Denize veya büyük göle kıyısı olan ilçeler
export const COASTAL_DISTRICTS: Record<string, string[]> = {
  'İstanbul': [
    'Adalar', 'Avcılar', 'Bakırköy', 'Beşiktaş', 'Beykoz', 'Beylikdüzü',
    'Beyoğlu', 'Büyükçekmece', 'Fatih', 'Kadıköy', 'Kartal', 'Küçükçekmece',
    'Maltepe', 'Pendik', 'Sarıyer', 'Silivri', 'Şile', 'Tuzla', 'Üsküdar',
    'Zeytinburnu',
  ],
  'Ankara': [],
  'İzmir': [
    'Aliağa', 'Balçova', 'Bayraklı', 'Çeşme', 'Çiğli', 'Dikili', 'Foça',
    'Gaziemir', 'Güzelbahçe', 'Karaburun', 'Karşıyaka', 'Konak', 'Menderes',
    'Menemen', 'Narlıdere', 'Seferihisar', 'Selçuk', 'Urla',
  ],
  'Bursa': [
    'Gemlik', 'Karacabey', 'Mudanya',
  ],
  'Antalya': [
    'Aksu', 'Alanya', 'Demre', 'Finike', 'Gazipaşa', 'Kaş', 'Kemer',
    'Konyaaltı', 'Kumluca', 'Manavgat', 'Muratpaşa', 'Serik',
  ],
  'Balıkesir': [
    'Ayvalık', 'Bandırma', 'Burhaniye', 'Edremit', 'Erdek', 'Gömeç',
    'Gönen', 'Havran', 'Marmara',
  ],
  'Kocaeli': [
    'Başiskele', 'Darıca', 'Derince', 'Dilovası', 'Gebze', 'Gölcük',
    'İzmit', 'Karamürsel', 'Körfez',
  ],
  'Mersin': [
    'Akdeniz', 'Anamur', 'Aydıncık', 'Bozyazı', 'Erdemli', 'Mezitli',
    'Silifke', 'Tarsus', 'Yenişehir',
  ],
  'Muğla': [
    'Bodrum', 'Dalaman', 'Datça', 'Fethiye', 'Köyceğiz', 'Marmaris',
    'Milas', 'Ortaca', 'Seydikemer',
  ],
  'Tekirdağ': [
    'Marmara Ereğlisi', 'Süleymanpaşa', 'Şarköy',
  ],
  'Eskişehir': [],
  'Sakarya': [
    'Karasu', 'Kocaali',
  ],
  'Samsun': [
    'Alaçam', 'Atakum', 'Bafra', 'Canik', 'Çarşamba', 'İlkadım',
    'Ondokuzmayıs', 'Tekkeköy', 'Terme', 'Yakakent',
  ],
  'Edirne': [
    'Enez', 'İpsala',
  ],
  'Kayseri': [],
  'Konya': [],
  'Kuzey Kıbrıs': [
    'Gazimağusa', 'Girne', 'İskele', 'Güzelyurt', 'Lefke',
  ],
};

// ─── İlçe bazlı orman bölgesi listesi (6831 Orman Kanunu riski) ───
// Orman alanlarının yoğun olduğu ilçeler (2B arazisi riski yüksek)
export const FORESTED_DISTRICTS: Record<string, string[]> = {
  'İstanbul': [
    'Arnavutköy', 'Beykoz', 'Çatalca', 'Çekmeköy', 'Eyüpsultan',
    'Sarıyer', 'Şile', 'Silivri',
  ],
  'Ankara': [
    'Çamlıdere', 'Kızılcahamam', 'Nallıhan', 'Beypazarı', 'Güdül',
    'Elmadağ', 'Ayaş',
  ],
  'İzmir': [
    'Bayındır', 'Bergama', 'Beydağ', 'Karaburun', 'Kemalpaşa',
    'Kiraz', 'Ödemiş', 'Tire',
  ],
  'Bursa': [
    'Büyükorhan', 'Harmancık', 'Keles', 'Orhaneli', 'Mustafakemalpaşa',
    'İnegöl', 'Orhangazi',
  ],
  'Antalya': [
    'Akseki', 'Döşemealtı', 'Gündoğmuş', 'İbradı', 'Kemer',
    'Korkuteli', 'Manavgat', 'Serik',
  ],
  'Balıkesir': [
    'Balya', 'Bigadiç', 'Dursunbey', 'İvrindi', 'Kepsut',
    'Sındırgı', 'Savaştepe',
  ],
  'Kocaeli': [
    'Kandıra', 'Kartepe', 'Başiskele',
  ],
  'Mersin': [
    'Çamlıyayla', 'Gülnar', 'Mut', 'Aydıncık', 'Erdemli',
    'Silifke', 'Anamur',
  ],
  'Muğla': [
    'Kavaklıdere', 'Köyceğiz', 'Menteşe', 'Seydikemer', 'Ula',
    'Yatağan', 'Fethiye', 'Marmaris', 'Datça',
  ],
  'Tekirdağ': [
    'Saray', 'Şarköy',
  ],
  'Eskişehir': [
    'İnönü', 'Mihalgazi', 'Mihalıççık', 'Sarıcakaya', 'Seyitgazi',
  ],
  'Sakarya': [
    'Akyazı', 'Geyve', 'Hendek', 'Karapürçek', 'Karasu', 'Kocaali',
    'Sapanca', 'Taraklı',
  ],
  'Samsun': [
    'Asarcık', 'Ayvacık', 'Kavak', 'Ladik', 'Salıpazarı',
    'Terme', 'Vezirköprü',
  ],
  'Edirne': [
    'Lalapaşa', 'Süloğlu',
  ],
  'Kayseri': [
    'Pınarbaşı', 'Sarız', 'Yahyalı', 'Develi', 'Tomarza',
  ],
  'Konya': [
    'Beyşehir', 'Bozkır', 'Derebucak', 'Hadim', 'Seydişehir',
    'Taşkent', 'Ahırlı',
  ],
  'Kuzey Kıbrıs': [
    'Girne', 'Lefke',
  ],
};

// ─── Yardımcı Fonksiyonlar ────────────────────────────────────────

export function getEarthquakeZone(city: string, district: string): EarthquakeZone | null {
  return EARTHQUAKE_ZONES[city]?.[district] ?? null;
}

export function getEarthquakeRiskLabel(zone: EarthquakeZone): string {
  const labels: Record<EarthquakeZone, string> = {
    1: '1. Derece Deprem Bölgesi (Çok Yüksek Tehlike)',
    2: '2. Derece Deprem Bölgesi (Yüksek Tehlike)',
    3: '3. Derece Deprem Bölgesi (Orta Tehlike)',
    4: '4. Derece Deprem Bölgesi (Düşük Tehlike)',
    5: '5. Derece Deprem Bölgesi (Çok Düşük Tehlike)',
  };
  return labels[zone];
}

export function isCoastalDistrict(city: string, district: string): boolean {
  return COASTAL_DISTRICTS[city]?.includes(district) ?? false;
}

export function isForestedDistrict(city: string, district: string): boolean {
  return FORESTED_DISTRICTS[city]?.includes(district) ?? false;
}
