import type { User, Listing, BuyerDemand, Match } from '@/types';

// ─── MOCK KULLANICILAR ────────────────────────────────

export const mockUsers: User[] = [
  {
    id: '1',
    auth_id: 'auth-1',
    email: 'ahmet@yilmazgayrimenkul.com',
    phone: '+90 532 123 4567',
    name: 'Ahmet Yılmaz',
    company_name: 'Yılmaz Gayrimenkul',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    license_status: 'approved',
    license_image_url: null,
    license_number: 'TYB-2024-001234',
    is_active: true,
    is_admin: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    auth_id: 'auth-2',
    email: 'elif@kayaemlak.com',
    phone: '+90 535 987 6543',
    name: 'Elif Kaya',
    company_name: 'Kaya Emlak',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    license_status: 'approved',
    license_image_url: null,
    license_number: 'TYB-2024-005678',
    is_active: true,
    is_admin: false,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-02-20T10:00:00Z',
  },
  {
    id: '3',
    auth_id: 'auth-3',
    email: 'mehmet@demirpartners.com',
    phone: '+90 541 555 1234',
    name: 'Mehmet Demir',
    company_name: 'Demir & Partners',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    license_status: 'approved',
    license_image_url: null,
    license_number: 'TYB-2023-009012',
    is_active: true,
    is_admin: false,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
  },
  {
    id: '4',
    auth_id: 'auth-4',
    email: 'zeynep.arslan@gmail.com',
    phone: '+90 543 222 3344',
    name: 'Zeynep Arslan',
    company_name: null,
    avatar_url: null,
    license_status: 'approved',
    license_image_url: null,
    license_number: 'TYB-2024-003456',
    is_active: true,
    is_admin: false,
    created_at: '2024-04-05T10:00:00Z',
    updated_at: '2024-04-05T10:00:00Z',
  },
  {
    id: '5',
    auth_id: 'auth-5',
    email: 'can@ozdemiremlak.com',
    phone: '+90 537 444 5566',
    name: 'Can Özdemir',
    company_name: 'Özdemir Emlak Ofisi',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    license_status: 'approved',
    license_image_url: null,
    license_number: 'TYB-2023-007890',
    is_active: true,
    is_admin: false,
    created_at: '2024-05-12T10:00:00Z',
    updated_at: '2024-05-12T10:00:00Z',
  },
];

// ─── MOCK İLANLAR (Kör — adres yok) ──────────────────

export const mockListings: Listing[] = [
  {
    id: '1',
    agent_id: '1',
    transaction_type: 'SALE',
    property_type: 'RESIDENTIAL',
    district: 'Kadıköy',
    neighborhood: 'Caferağa',
    room_count: '3+1',
    net_area: 120,
    gross_area: 145,
    floor: 4,
    total_floors: 7,
    building_age: 5,
    has_parking: true,
    has_elevator: true,
    heating_type: 'Doğalgaz (Kombi)',
    price: 12500000,
    description: 'Deniz manzaralı, yenilenmiş, ferah daire. Metro yakınında.',
    status: 'ACTIVE',
    created_at: '2024-06-01T14:30:00Z',
    updated_at: '2024-06-01T14:30:00Z',
    agent: mockUsers[0],
  },
  {
    id: '2',
    agent_id: '2',
    transaction_type: 'RENT',
    property_type: 'RESIDENTIAL',
    district: 'Beşiktaş',
    neighborhood: 'Levent',
    room_count: '2+1',
    net_area: 85,
    gross_area: 105,
    floor: 12,
    total_floors: 20,
    building_age: 2,
    has_parking: true,
    has_elevator: true,
    heating_type: 'Merkezi Sistem',
    price: 42000,
    description: 'Güvenlikli site içinde, eşyalı residence. Havuz ve spor salonu mevcut.',
    status: 'ACTIVE',
    created_at: '2024-06-02T09:15:00Z',
    updated_at: '2024-06-02T09:15:00Z',
    agent: mockUsers[1],
  },
  {
    id: '3',
    agent_id: '3',
    transaction_type: 'SALE',
    property_type: 'RESIDENTIAL',
    district: 'Sarıyer',
    neighborhood: 'Tarabya',
    room_count: '5+2',
    net_area: 280,
    gross_area: 340,
    floor: 1,
    total_floors: 3,
    building_age: 8,
    has_parking: true,
    has_elevator: false,
    heating_type: 'Yerden Isıtma',
    price: 32000000,
    description: 'Boğaz manzaralı, bahçeli, havuzlu müstakil villa.',
    status: 'ACTIVE',
    created_at: '2024-06-03T11:00:00Z',
    updated_at: '2024-06-03T11:00:00Z',
    agent: mockUsers[2],
  },
  {
    id: '4',
    agent_id: '4',
    transaction_type: 'SALE',
    property_type: 'COMMERCIAL',
    district: 'Şişli',
    neighborhood: 'Mecidiyeköy',
    room_count: null,
    net_area: 200,
    gross_area: 230,
    floor: 3,
    total_floors: 12,
    building_age: 3,
    has_parking: true,
    has_elevator: true,
    heating_type: 'Merkezi Sistem',
    price: 8500000,
    description: 'Plaza katı, açık ofis düzeni. Metroya 2 dakika yürüme mesafesi.',
    status: 'ACTIVE',
    created_at: '2024-06-04T16:45:00Z',
    updated_at: '2024-06-04T16:45:00Z',
    agent: mockUsers[3],
  },
  {
    id: '5',
    agent_id: '5',
    transaction_type: 'SALE',
    property_type: 'LAND',
    district: 'Esenyurt',
    neighborhood: 'Güzelyurt',
    room_count: null,
    net_area: null,
    gross_area: 500,
    floor: null,
    total_floors: null,
    building_age: null,
    has_parking: false,
    has_elevator: false,
    heating_type: null,
    price: 4200000,
    description: 'İmarlı arsa, konut alanı. Ana caddeye cepheli, 500m².',
    status: 'ACTIVE',
    created_at: '2024-06-05T08:20:00Z',
    updated_at: '2024-06-05T08:20:00Z',
    agent: mockUsers[4],
  },
  {
    id: '6',
    agent_id: '1',
    transaction_type: 'RENT',
    property_type: 'COMMERCIAL',
    district: 'Kadıköy',
    neighborhood: 'Kozyatağı',
    room_count: null,
    net_area: 150,
    gross_area: 170,
    floor: 1,
    total_floors: 5,
    building_age: 10,
    has_parking: true,
    has_elevator: true,
    heating_type: 'Merkezi Sistem',
    price: 65000,
    description: 'E-5 cepheli dükkan, geniş vitrin. Depo alanı mevcut.',
    status: 'ACTIVE',
    created_at: '2024-06-06T13:30:00Z',
    updated_at: '2024-06-06T13:30:00Z',
    agent: mockUsers[0],
  },
];

// ─── MOCK ALICI TALEPLERİ (Uygulamanın Kalbi) ────────

export const mockDemands: BuyerDemand[] = [
  {
    id: '1',
    agent_id: '2',
    transaction_type: 'SALE',
    property_type: 'RESIDENTIAL',
    district: 'Kadıköy',
    neighborhoods: ['Caferağa', 'Moda', 'Fenerbahçe'],
    min_budget: 10000000,
    max_budget: 15000000,
    min_rooms: '3+1',
    min_area: 100,
    max_floor: null,
    notes: 'Deniz manzaralı, metro yakınında, 2020 sonrası bina tercih ediliyor. Müşteri nakit ödeme yapacak.',
    status: 'ACTIVE',
    expires_at: null,
    created_at: new Date(Date.now() - 180000).toISOString(), // 3dk önce
    updated_at: new Date(Date.now() - 180000).toISOString(),
    agent: mockUsers[1],
  },
  {
    id: '2',
    agent_id: '3',
    transaction_type: 'RENT',
    property_type: 'COMMERCIAL',
    district: 'Şişli',
    neighborhoods: ['Mecidiyeköy', 'Fulya'],
    min_budget: 40000,
    max_budget: 80000,
    min_rooms: null,
    min_area: 150,
    max_floor: 3,
    notes: 'Restoran veya kafe işletmesi için uygun, mutfak altyapılı mekan aranıyor.',
    status: 'ACTIVE',
    expires_at: null,
    created_at: new Date(Date.now() - 7200000).toISOString(), // 2sa önce
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    agent: mockUsers[2],
  },
  {
    id: '3',
    agent_id: '4',
    transaction_type: 'SALE',
    property_type: 'RESIDENTIAL',
    district: 'Ataşehir',
    neighborhoods: ['Küçükbakkalköy', 'İçerenköy'],
    min_budget: 5000000,
    max_budget: 8000000,
    min_rooms: '2+1',
    min_area: 80,
    max_floor: 10,
    notes: 'Finans merkezine yakın, site içi, güvenlikli. Genç çift, ilk ev alımı.',
    status: 'ACTIVE',
    expires_at: null,
    created_at: new Date(Date.now() - 86400000).toISOString(), // 1g önce
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    agent: mockUsers[3],
  },
  {
    id: '4',
    agent_id: '5',
    transaction_type: 'SALE',
    property_type: 'LAND',
    district: 'Beylikdüzü',
    neighborhoods: [],
    min_budget: 3000000,
    max_budget: 6000000,
    min_rooms: null,
    min_area: 300,
    max_floor: null,
    notes: 'İmarlı arsa, müstakil konut veya küçük apartman projesi için. Yola cepheli tercih edilir.',
    status: 'ACTIVE',
    expires_at: null,
    created_at: new Date(Date.now() - 172800000).toISOString(), // 2g önce
    updated_at: new Date(Date.now() - 172800000).toISOString(),
    agent: mockUsers[4],
  },
  {
    id: '5',
    agent_id: '1',
    transaction_type: 'SALE',
    property_type: 'RESIDENTIAL',
    district: 'Bakırköy',
    neighborhoods: ['Florya', 'Yeşilköy'],
    min_budget: 15000000,
    max_budget: 25000000,
    min_rooms: '4+1',
    min_area: 180,
    max_floor: 5,
    notes: 'Sahile yakın, geniş balkonlu. Müşteri üst segment, yüksek bütçeli yatırımcı.',
    status: 'ACTIVE',
    expires_at: null,
    created_at: new Date(Date.now() - 3600000).toISOString(), // 1sa önce
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    agent: mockUsers[0],
  },
];

// ─── MOCK EŞLEŞMELER ─────────────────────────────────

export const mockMatches: Match[] = [
  {
    id: '1',
    requester_id: '1',
    target_id: '2',
    match_type: 'DEMAND',
    listing_id: '1',
    demand_id: '1',
    status: 'PENDING',
    message: 'Caferağa\'da 3+1 ilanım bu talebe uygun olabilir.',
    responded_at: null,
    created_at: new Date(Date.now() - 120000).toISOString(),
    requester: mockUsers[0],
    target: mockUsers[1],
    listing: mockListings[0],
    demand: mockDemands[0],
  },
  {
    id: '2',
    requester_id: '3',
    target_id: '1',
    match_type: 'LISTING',
    listing_id: '1',
    demand_id: null,
    status: 'ACCEPTED',
    message: 'Müşterim bu daire ile ilgileniyor.',
    responded_at: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    requester: mockUsers[2],
    target: mockUsers[0],
    listing: mockListings[0],
  },
];
